- ipython_kernel/pickleutil.py
- ipython_kernel/tests/test_serialize.py
test updated to cover failing case
> handle memoryviews in numpy frombuffer on Python 2

- ipython_kernel/comm/comm.py
- ipython_kernel/comm/manager.py
- ipython_kernel/datapub.py
- ipython_kernel/displayhook.py
- ipython_kernel/inprocess/ipkernel.py
- ipython_kernel/iostream.py
- ipython_kernel/kernelapp.py
- ipython_kernel/kernelbase.py
- ipython_kernel/session.py
- ipython_kernel/zmqshell.py
> import session from jupyter_client

- requirements.txt
> remove genutils from requirements

- ipython_kernel/ipkernel.py
> Remove reference to widgets.

- ipython_kernel/pickleutil.py
> remove ipyparallel handling in pickleutil

- ipython_kernel/tests/test_kernelspec.py
> fix testing patch of jupyter env

- ipykernel/kernelspec.py
python -m ipykernel.kernelspec [--user]
> allow installing the kernelspec with `-m`

- ipykernel/kernelspec.py
for multiple IPython kernels at the same time.
Related to jupyter/jupyter_client#26
> allow specifying the name of the IPython kernel

- ipykernel/kernelspec.py
> support kernelspec install prefix

- ipykernel/ipkernel.py
sibling PRs: 
https://github.com/jupyter/notebook/pull/120
https://github.com/ipython/ipywidgets/pull/38
> Hardcode widgets

- ipykernel/ipkernel.py
> only catch ImportError for widget hardcoding

- ipykernel/tests/test_message_spec.py
See https://github.com/ipython/traitlets/pull/51
> Use instances of traits instead of trait classes

- README.md
From conversation in [gitter](https://gitter.im/ipython/ipython) with @minrk.
> add instructions for installation from source

- README.md
> remove --pre

- ipykernel/comm/manager.py
> demote no such comm message to warning

- ipykernel/inprocess/client.py
- ipykernel/inprocess/manager.py
- define blocking_class (see jupyter/jupyter_client#55)
- define is_complete
sibling of jupyter/qtconsole#33 jupyter/jupyter_client#55
> support blocking is_complete in inprocess

- ipykernel/kernelspec.py
- ipykernel/tests/test_kernelspec.py
> Fixes typo in InstallIPythonKernelSpecApp

- ipykernel/comm/comm.py
was missing metadata, buffers args
> support a full message in initial comm open

- ipykernel/zmqshell.py
> update lingering IPython.parallel import

- docs/changelog.rst
with this and #80, we should be able to release 4.2 tonight or tomorrow.
cc @SylvainCorlay
> release notes for 4.2

- ipykernel/jsonutil.py
- ipykernel/tests/test_jsonutil.py
This lets numpy numeric types to work with json cleaning functions, for example.
CC @ChakriCherukuri
> Check for number types using the python type hierarchy

- ipykernel/kernelapp.py
Just show the regular traceback
FormattedTB adds extra noise designed for debugging interactive code.
Do we want any additional "I died!" or "bug reports here..." messages on a crash like this?
cc @ssanderson @fperez
> Don't use FormattedTB as kernel crash handler

- ipykernel/kernelspec.py
> Fill in application name for argparse help

- docs/changelog.rst
- ipykernel/kernelapp.py
Windows has no faulthandler.register
closes #107
We should release this as 4.3.1 today.
> fix faulthandler patch on Windows

- ipykernel/kernelapp.py
- ipykernel/kernelbase.py
- ipykernel/pylab/config.py
- setup.py
This depends on https://github.com/ipython/traitlets/pull/53, which was included in traitlets 4.1.0.
> Use traitlets 4.1 .tag() for config metadata

- .travis.yml
> Switch to codecov

- ipykernel/zmqshell.py
follow-up to #144
- update security_dir check for jupyter paths
- remove no longer relevant mention of profiles
> More Jupyter updates for %connect_info

- ipykernel/kernelapp.py
- ipykernel/tests/test_message_spec.py
cf https://github.com/jupyter/jupyter_client/issues/179
> comply with msg spec for connect_reply

- ipykernel/kernelapp.py
> don't print ctrl-C message if --quiet

- ipykernel/eventloops.py
Goes with https://github.com/ipython/ipython/pull/9885
> Add support for ipympl backend

- docs/changelog.rst
will release once this is merged
> Changelog for 4.5

- ipykernel/comm/comm.py
We need this to generate pure server-side widget state.
> Allow comms to be instanciated outside of a kernel

- docs/changelog.rst
- ipykernel/_version.py
accumulated bugfixes
cc @SylvainCorlay
> Prepare to release 4.5.1

- docs/changelog.rst
Just for the comms-outside-kernels fix (#211)
> changelog for 4.5.2

- ipykernel/inprocess/tests/test_kernelmanager.py
- ipykernel/iostream.py
> make sure IOPubThreads are cleaned up in inprocess tests

- ipykernel/tests/__init__.py
Fixes running tests with packages --user installed.
Prompted by jupyter/notebook#2111
> Patch PYTHONPATH when running tests

- docs/changelog.rst
@minrk I took a pass at creating the changelog.
> Add changelog 4.6.0

- ipykernel/eventloops.py
These are no-ops in IPython >= 5.2 if `get_ipython().active_eventloop` is defined, so the eventloops never start.
Replace them with private functions that are guaranteed to actually run the eventloop,
effectively replicating the `start_event_loop` behavior from IPython < 5.2, without the need for is-it-running checks due to being a public API.
closes #240
cf https://github.com/ipython/ipython/issues/9974 , https://github.com/ipython/ipython/pull/10419
> Remove calls to `start_event_loop_qt|wx` from IPython.lib.guisupport

- ipykernel/eventloops.py
Based on https://github.com/ipython/ipykernel/issues/21#issue-82784960 by @peteut.
> Add asyncio loop integration.

- ipykernel/jsonutil.py
https://github.com/jupyter/notebook/pull/2702 and https://github.com/ipython/ipython/pull/10716 depends on this
> Support image/gif mimetype

- ipykernel/displayhook.py
- ipykernel/jsonutil.py
> fix a couple of undefined names

- .travis.yml
- appveyor.yml
while we work out what's up with 5.0
> pin tornado for testing

- .travis.yml
- ipykernel/kernelbase.py
- ipykernel/tests/test_kernel.py
- '' is inserted to sys.path after the start in IPython 7.2
- completion start point is flexible, so
verify the spec rather than the value
closes #387
> update kernel tests for IPython upgrades

- ipykernel/kernelbase.py
> PR: Raw_input function working with special characters in python 2.7

- docs/changelog.rst
> Add changelog for 5.1.2

- setup.py
cf https://github.com/conda-forge/ipykernel-feedstock/issues/44
> Make ipykernel use sys.executable

- .travis.yml
Switch 3.8 to released versions (#454), and remove a couple of older configurations.
> Update Python versions tested on Travis

- ipykernel/kernelapp.py
cc @jasongrout 
this should not have been required for a while now.
> Remove ipywidgets hack

- ipykernel/tests/test_kernel.py
> PR: Skip test_unc_paths if OS is not Windows

- .travis.yml
- ipykernel/ipkernel.py
More details on the issue: https://github.com/ipython/ipykernel/issues/520
> fix #520: run post_execute and post_run_cell on async cells

- ipykernel/eventloops.py
tk support has been broken on Windows since the timer based event loop hook was replaced with a better but POSIX only event driven one. This PR leaves the POSIX one in place where that is available, but falls back to the timer where it is not.
Related:
#518
#358
Semi-reverts commit [e719892c](https://github.com/ipython/ipykernel/commit/e719892c6f56ac5185a51584f5ddd136fb77b603)
> Restore timer based event loop as a Windows-compatible fallback.

- ipykernel/eventloops.py
> Only run Qt eventloop in the shell stream

- docs/changelog.rst
cf https://github.com/ipython/ipykernel/issues/565
> Add changelog for 5.4

- ipykernel/tests/utils.py
> Attempt longer timeout

- .github/workflows/ci.yml
We should be running CI against all active branches.
> Run GitHub Actions on all branches

- ipykernel/kernelbase.py
@SylvainCorlay ?
(originated in #585)
> missing self

- setup.py
> Fixup master build

- ipykernel/ipkernel.py
This function should not be async.
> Fixes debugging with native coroutines

- ipykernel/comm/comm.py
> Fixup get_parent_header call

- CHANGELOG.md
Adds auto-generated documentation for merged PRs, with some formatting applied.
> Update Changelog for 6.0 Release

- CHANGELOG.md
Automated Changelog Entry for 6.3.1 on master
After merging this PR run the "Draft Release" Workflow on your fork of `jupyter_releaser` with the following inputs
| Version Spec | 6.3.1 |
| Since | v6.3.0 |
> Automated Changelog Entry for 6.3.1 on master

- CHANGELOG.md
Automated Changelog Entry for 6.5.0 on master
| Version Spec | 6.5.0 |
| Since | v6.4.2 |
> Automated Changelog Entry for 6.5.0 on master

- ipykernel/compiler.py
> fix #800 the temp file name generated by murmur2 in python and ts is not same

- ipykernel/debugger.py
This PR adds the support for the Modules request https://microsoft.github.io/debug-adapter-protocol/specification#Requests_Modules as discussed on https://github.com/jupyterlab/jupyterlab/pull/11566#discussion_r759661311
> Add support for the debug modules request

- .git-blame-ignore-revs
> Add ignore-revs file

- ipykernel/inprocess/tests/test_kernel.py
- ipykernel/ipkernel.py
- ipykernel/kernelbase.py
- pyproject.toml
- setup.py
> Make cell_id optional

- .github/workflows/ci.yml
- .pre-commit-config.yaml
- CONTRIBUTING.md
- Make the non-automatic hooks manual and run on CI
- Update contributing docs
> Clean up pre-commit

- ipykernel/inprocess/socket.py
- ipykernel/iostream.py
- ipykernel/kernelbase.py
Updates for `mypy` and `pyzmq` changes.
> Clean up typings

- hatch_build.py
> Force debugger metadata in built wheel

- .github/workflows/ci.yml
- pyproject.toml
> Fix inclusion of launcher file and check in CI

- pyproject.toml
See https://github.com/jupyter/jupyter_core/issues/310
> Ignore the new Jupyter_core deprecation warning in CI

- .github/workflows/ci.yml
- README.md
- codecov.yml
- pyproject.toml
cf https://github.com/jupyterlab/maintainer-tools/pull/189
> Use local coverage

- ipykernel/iostream.py
> Make iostream shutdown more robust

- ipykernel/debugger.py
Just a minor spelling correction
> Correct spelling mistake

- ipykernel/pickleutil.py
(cherry picked from commit 384bdb13256a5eb0bf18a3d78969f3f0dceeaa2c)
> Fix side effect import for pickleutil

- ipykernel/ipkernel.py
Manual backport for https://github.com/ipython/ipykernel/pull/1223
> Backport PR #1223 on branch 6.x (Do not import debugger/debugpy unless needed)

- .github/workflows/prep-release.yml
- .github/workflows/publish-changelog.yml
- .github/workflows/publish-release.yml
> [6.x] Update Release Scripts 

- ipykernel/_version.py
Main contains semver major changes. Updating version to reflect this.
Fixes: #1240
> Update version to 7.0.0

- ipykernel/subshell_manager.py
This is triggering a linting error, and pollute other PRs with errors.
> Fix types lints

- ipykernel/zmqshell.py
IPykernel is the only user, and this will let us remove it from IPython.
Closes #1304
> Copy payloadpage.page from IPython

- .pre-commit-config.yaml
It has not in a loong time, but I'm not sure why.
> Try to force precommit-ci to send autoupdate PRs.

- ipykernel/datapub.py
- ipykernel/log.py
- ipykernel/pickleutil.py
- ipykernel/serialize.py
> Refine deprecation error messages.

- .github/workflows/downstream.yml
- ipykernel/inprocess/client.py
- tests/test_subshells.py
Also remove the -x, because if there is many failures, we want to knw that.
> Disable 3 failing downstream tests, but keep testing the rest.

- .github/workflows/downstream.yml
Have been disabled from 2 years.
> Try to reenable tests from downstream ipywidgets

- tests/test_start_kernel.py
See https://github.com/ipython/ipython/pull/14754
> Fix expected text depending on IPython version.

- ipykernel/kernelapp.py
- ipykernel/kernelbase.py
> Make kernelbase._eventloop_set event thread-safe

- tests/utils.py
We ahve not been using nose for years.
> Remove nose import.

- .github/workflows/ci.yml
- CHANGELOG.md
- ipykernel/socket_pair.py
> Test more python versions on 6.x branch
