ipython/ipykernel

- ipython_kernel/pickleutil.py
Now that `cloudpickle` is in its [own package up on PyPI](https://pypi.python.org/pypi/cloudpickle) it can be installed and used directly.
Benefits:
* supports Python 3
* has its own suite of tests (nothing public prior)
* active development
/cc @ogrisel
> import cloudpickle directly

- ipython_kernel/comm/comm.py
- ipython_kernel/datapub.py
- ipython_kernel/displayhook.py
- ipython_kernel/inprocess/ipkernel.py
- ipython_kernel/jsonutil.py
- ipython_kernel/kernelbase.py
- ipython_kernel/tests/test_jsonutil.py
- ipython_kernel/zmqshell.py
these parts of the code are only used in the IPython kernel, so don't belong in Jupyter Client, where jsonutil was moved.
jupyter_client.jsonutil preserves the date handling
This also disables the casting fallback, which ensures json_clean could never raise. That was probably never a good idea, and just hides bugs.
> migrate json_clean to ipython_kernel

- ipykernel/jsonutil.py
- ipykernel/tests/test_jsonutil.py
datetime objects are allowed, and serialized to ISO8601
closes ipython/ipywidgets#35
> handle datetime in json_clean

- ipykernel/heartbeat.py
instead of FORWARDER(REP)
due to change in libzmq-4.0.6
[more info](https://groups.google.com/forum/#!topic/jupyter/UM-ShiI_Mrs)
> use QUEUE(ROUTER) for heartbeat

- setup.py
dependency only lists ipython, which will not upgrade ipython past 3.x
Using 4.0dev, since '>=4.0' will reject '4.0b1' as < 4.0, eliminating the usefulness of the current `--pre` behavior. This is temporary, anyway, and should be bumped to 4.0-proper once we ship IPython.
> require IPython 4

- ipykernel/ipkernel.py
- ipykernel/kernelapp.py
instead of hardcoding a special method.
It's still on by default, which is the main goal.
sibling PR: ipython/ipywidgets#101
> use ipywidgets as an extension

- setup.py
This shouldn't be merged yet, since 4.0f doesn't exist. But we should merge and make a new ipykernel release immediately when we cut IPython 4.0.
> depend on IPython 4.0 final

- ipykernel/kernelapp.py
If a connection file is specified with an absolute path via the '-f'
command line option, ipykernel still makes sure that the default connection
directory exists, even though it is not needed. Instead, simply create the
directory for the path to the connection file that we end up actually
using.
This introduces a slight change in behaviour in that if one specifies a
connection file via the '-f' option and the given directory does not
exist, it will be created instead of an error being generated.
In my case, I am specifying a different path to the connection file because the default path is not writable. While I could (and probably should) change the default path with the corresponding environment variables, it still left me wondering whether the default connection directory should be …
> Avoid creating default connection dir if not needed

- ipykernel/pickleutil.py
- ipykernel/tests/test_pickleutil.py
otherwise memoryviews will come out as '<memoryview...>' on Python 2.
includes regression test
closes ipython/ipyparallel#30
> cast buffers to bytes in CannedBytes

- ipykernel/kernelapp.py
- ipykernel/kernelspec.py
replacement for 'ipython kernelspec install-self'
Previously only available as `python -m ipykernel.kernelspec`
cc @stefanv @jasongrout
> add `ipython kernel install`

- ipykernel/kernelapp.py
Is there a particular reason this is the other way around?
When the connection file is first written and then logged, then external programs could monitor the log output and use the connection file (e.g. connect a client) without race condition.
> Write connection file before writing its location to the log

- ipykernel/inprocess/client.py
- ipykernel/kernelbase.py
- ipykernel/tests/test_message_spec.py
Adding a `comm_list_[request/reply]` shell message. This requires https://github.com/jupyter/jupyter_client/pull/34.
> Adding comm_info_request and comm_info_reply messages

- ipykernel/pickleutil.py
This change is a result of investigating this StackOverflow question regarding `parallel.Reference` objects in a list of dictionaries: http://stackoverflow.com/questions/31343529/ipython-parallel-reference-with-map-vs-apply
```python
from IPython import parallel
from IPython.parallel import Client
from IPython.parallel import Reference
rc = Client()
dview = rc.direct_view()
dview.block = True
dview['l'] = [0, 1]
kws = [{'l': Reference('l')}]
def second(kws):
l = kws['l']
return l[1]
dview.map(second, kws) # results in TypeError: 'Reference' object does not support indexing
```
When a list of dictionaries is provided as an argument to a parallel map, the `Reference` objects in the `dict`s aren't reached by the `uncan` function. Adding `dict` to the list of uncanners produces the correct …
> Add uncan_dict to uncan_map

- ipykernel/kernelspec.py
it's annoying to install multiple IPython kernelspecs that all look the same in the dropdown.
> allow `ipython kernelspec install --display-name FOO`

- examples/embedding/internal_ipkernel.py
Sometimes new Qt console process can't find the connection file in its path list. 
Use abs path to replace it.
> Give abs json file path to nwe Qt console.

- ipykernel/__init__.py
- ipykernel/_version.py
- ipykernel/kernelbase.py
It's part of the kernel, not the core package.
> Don't get kernel_protocol_version from IPython

- ipykernel/datapub.py
- ipykernel/displayhook.py
- ipykernel/inprocess/socket.py
- ipykernel/zmqshell.py
and stop using it.
avoids importing inprocess when it's not used.
> Deprecate SocketABC

- ipykernel/__init__.py
`import *` doesn't import attributes which start with an underscore, so it
won't import `__version__`
> Fix version attributes import

- ipykernel/comm/manager.py
@minrk @jdfreder 
We were missing the `target_name`attribute when creating a Comm on reception of `comm_open` messages.
> Adding missing target name when creating a new comm from the front-end

- ipykernel/kernelspec.py
`ipython kernel install --name foo` installs kernel with name foo and display_name foo, without needing to specify two arguments.
closes #75
> default display_name to kernel_name if specified

- ipykernel/kernelspec.py
I installed the Python 2 kernel spec with:
```
python2 -m ipykernel.kernelspec --user
```
I noticed that the display name was showing up as 'python2' instead of 'Python 2'.
The name flag in the command line arguments now has an explicit default of `KERNEL_NAME`. This gets passed to install(), which expects None to mean the default. It treats it as a non-default name and sets the display name as well.
This changes the logic of install() so that the display name is not set to the default `KERNEL_NAME`, and it shows up as 'Python 2' again.
> Don't override default display name with default kernel name

- ipykernel/tests/utils.py
Not sure about this fix, but this fixed an issue I was facing. I got the following error before this fix:
```
File "/usr/lib/python3.5/site-packages/ipykernel/tests/utils.py", line 41, in start_new_kernel
return manager.start_new_kernel(startup_timeout=STARTUP_TIMEOUT, **kwargs)
File "/usr/lib/python3.5/site-packages/jupyter_client/manager.py", line 430, in start_new_kernel
km.start_kernel(**kwargs)
File "/usr/lib/python3.5/site-packages/jupyter_client/manager.py", line 244, in start_kernel
**kw)
File "/usr/lib/python3.5/site-packages/jupyter_client/manager.py", line 190, in _launch_kernel
return launch_kernel(kernel_cmd, **kw)
File "/usr/lib/python3.5/site-packages/jupyter_client/launcher.py", line 123, in launch_kernel
proc = Popen(cmd, **kwargs)
File …
```
> Use iptest_stdstreams_fileno as a function

- ipykernel/tests/test_connect.py
jupyter_client will add `kernel_name` to connection files (jupyter/jupyter_client#96)
Instead of checking full-dict equality, check the keys we know/care about,
so the tests aren't sensitive to backward-compatible additions.
> Handle added but ignored keys in connection file tests

- ipykernel/kernelapp.py
- ipykernel/tests/test_kernel.py
faulthandler requires access to C-level FD, which doesn't make sense for forwarded stdout/stderr. Patch default to be underlying `__stderr__` instead of overridden `stderr`.
closes #91
> patch faulthandler defaults to underlying stderr

- ipykernel/iostream.py
- ipykernel/tests/test_kernel.py
by stopping the thread explicitly at exit
I'm not sure why or how the daemon thread is preventing exit, but it is.
Previously failing test included.
> prevent IOThread from zombifying kernel

- ipykernel/codeutil.py
- ipykernel/datapub.py
- ipykernel/ipkernel.py
- ipykernel/kernelbase.py
- ipykernel/log.py
- ipykernel/pickleutil.py
- ipykernel/serialize.py
- ipykernel/zmqshell.py
- deprecation warnings on serialization, data pub
- Move ipyparallel-specific metadata to methods easier to override in subclasses
- deprecate handling messages not in spec: apply, clear, abort.
related: ipython/ipyparallel#61
closes #17
> Deprecate ipyparallel-specific code

- ipykernel/iostream.py
- ipykernel/tests/test_kernel.py
tracker method doesn't appear to be reliable for small messages, since zmq does some optimizations to always copy small messages.
This means creating/destroying new context/socket for each subprocess message, which is inefficient but shouldn't be too costly.
I've run the tests with this on Jenkins with the same env that was failing previously. Prior to this patch, the failure occurred pretty consistently around 10% of the time. It's now passed 50 times and counting without failure, so the fix seems to be successful.
closes #98 (hopefully)
> use ctx.term to flush pipe messages

- ipykernel/zmqshell.py
We're getting rid of the %guiref magic - see jupyter/qtconsole#98
> Don't show %guiref in banner

- ipykernel/zmqshell.py
I think automatically adding an active virtualenv to sys.path makes less sense in a kernel than it does in terminal IPython (and I'm less certain than I was even for terminal IPython).
If Jupyter is installed inside a virtualenv, it will still launch the default kernel in there too, but this would mean that you can no longer run e.g. 'jupyter console' with a virtualenv active and find packages from that virtualenv.
> Don't try to detect virtualenvs when starting a kernel

- ipykernel/connect.py
It's unused, and the one in jupyter_client should be used instead.
The only case where it might be used is searching for connection files by profile, which no longer makes sense since connection files aren't stored in IPython profiles.
closes #103
> deprecate find_connection_file

- docs/changelog.rst
- ipyparallel
- find_connection_file
cc @takluyver
release 4.3 after this?
> note deprecations in 4.3 changelog

- ipykernel/kernelapp.py
The latter is deprecated (ipython/ipython#9367)
> Use sys.stderr instead of IPython.utils.io.stderr

- .gitignore
- ipykernel/displayhook.py
- ipykernel/tests/test_kernel.py
- ipykernel/tests/test_message_spec.py
- ipykernel/tests/test_serialize.py
- ipykernel/tests/test_zmq_shell.py
- ipykernel/zmqshell.py
This is the initial work for #113.
> Message hook in display publisher

- ipykernel/comm/comm.py
- ipykernel/comm/manager.py
- ipykernel/inprocess/client.py
- ipykernel/inprocess/ipkernel.py
- ipykernel/inprocess/manager.py
- ipykernel/ipkernel.py
- ipykernel/kernelapp.py
- ipykernel/kernelbase.py
- ipykernel/zmqshell.py
`_foo_changed` -> `@observe('foo')` + signature change.
`_bar_default` -> `@default('bar')`
> Use traitlets>=4.1 APIs

- ipykernel/iostream.py
Please bear with me, as this is my first PR. This new locking in this PR appears to fix https://github.com/ipython/ipython/issues/9397, https://github.com/ipython/ipython/issues/9168
The lock/unlock does slow down output, but it should only be noticeable for notebooks that are writing data very quickly (i.e., the ones most likely to run into this issue).
TBH I don't fully understand the threading model in ipykernel, but the fact that the issue was hard to reproduce consistently (plus the fact that the locking seems to fix it) led me to believe it was a multithreading issue. 
Apologies in advance if I'm totally off-base on how the threading in ipykernel works.
> Add locking around output buffer

- ipykernel/kernelspec.py
For better symmetry with nbextensions, etc.
> Add `--sys-prefix` flag to `ipython kernel install`

- ipykernel/iostream.py
- ipykernel/kernelapp.py
This pull request fixes this issue: https://github.com/jupyter/notebook/issues/1397
For the sake of completeness, I'll repeat the issue here (edited according to the discussion on https://github.com/jupyter/notebook/issues/1397).
When running the example from the python logging documentation page in a jupyter notebook, the messages go to the notebook console as opposed to the notebook's webpage output via the capture mechanism. Just create an empty notebook, run the example below, you'll see what I mean.
```python
import logging
logging.basicConfig(format='%(levelname)s:%(message)s', level=logging.DEBUG)
logging.debug('This message should appear in the notebook')
logging.info('So should this')
logging.warning('And this, too')
```
What should happen: The messages appear in the notebook. …
> The python logging module no longer seems to work properly inside a notebook

- ipykernel/comm/comm.py
- ipykernel/comm/manager.py
- ipykernel/ipkernel.py
Howdy,
This is a general fix-up across the Comm and CommManager classes - there was quite a lot of redundant/duplicate code which has been cleaned up. There’s also a few performance items here - eg.  multiple identical dict lookups in the same function.
I deliberately haven’t made whitespace changes, but the editor has auto-cleaned up some trailing whitespace.
The biggest changes (which need input from @minrk @takluyver) are the removal of `session` and `iopub_socket` from Comm and CommManager. The tests pass and i can't find any places where these items are used directly, but it could do with some thought from you.
Their use on CommManager was only to be passed into the Comm objects (which happened in 2 places), and their use on Comm objects is restricted to a single method, so it's …
> General Fixes for Comms

- docs/changelog.rst
- ipykernel/inprocess/constants.py
- ipykernel/inprocess/ipkernel.py
- ipykernel/inprocess/manager.py
Use a nonempty dummy `Session` key for inprocess kernels. At present, instantiating a `Session` object with an empty key triggers a security warning that is not relevant to inprocess kernels.
Fixes #130
Fixes jupyter/qtconsole#119
> Dummy inprocess Session key

- .travis.yml
- ipykernel/pylab/config.py
- setup.cfg
it seem to show the IPython deprecation warnings for me locally, though even if these are in 4.2 they don't seem to appear on travis...
> Enable deprecation warnings

- ipykernel/comm/manager.py
This reverts part of 91c61ac16559576fa817d1712db7cf3df1142fdf (from https://github.com/ipython/ipykernel/pull/126), which introduced a logic bug which broke handling comm messages, widgets, etc. The logic in the refactoring was complicated enough that the invalid-checking function returned the opposite of what it should have returned.
Since the original code in each function was only about 10 lines, I think it’s more complicated to introduce three new undocumented functions instead of just repeating similar logic twice.
> Rewrite comm handling to make it clearer and fix a logic inversion bug

- ipykernel/comm/comm.py
- ipykernel/kernelapp.py
- ipykernel/kernelbase.py
- ipykernel/zmqshell.py
rather than from zmq
rely on zmq_ioloop.install() to register zmq implementation as default.
> import IOLoop from tornado

- README.md
Without this patch, anyone following the installation/test instruction
will see the following error:
```
nosetests: error: Error reading config file 'setup.cfg': no such option 'warningfilters'
```
<3
> update test instructions

- ipykernel/zmqshell.py
it was still referring to ipython entry points.
> update %connect_info output for jupyter

- ipykernel/gui/gtk3embed.py
Without this patch, newer versions of pygobject3 lead to the following warnings:
```
In [3]: %gui gtk3
In [4]: 
/a/lib/python2.7/site-packages/ipykernel/gui/gtk3embed.py:17: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
from gi.repository import GObject, Gtk
In [4]: 
```
> gtk3: Avoid warnings from newer GObject-introspection imports.

- ipykernel/comm/comm.py
IOPub is threadsafe as of 4.3
cf https://github.com/ipython/ipywidgets/issues/642
> Remove thread check for comm sends

- ipykernel/ipkernel.py
- ipykernel/zmqshell.py
Closes gh-143
I forget when we introduced ExecutionResult to IPython, but this requires a version of IPython with that machinery.
> Simplify detection of errors for execute_reply messages

- ipykernel/displayhook.py
- ipykernel/kernelapp.py
This fixes a crash I was seeing with the xonsh kernel.
Closes gh-161
> Ensure basic displayhook sends valid execute_result messages

- ipykernel/inprocess/manager.py
avoids leaking threads
closes #160
> inprocess: cleanup iopub thread on shutdown

- ipykernel/kernelspec.py
- ipykernel/tests/test_kernelspec.py
E.g.
```
$ ipython kernel install --name=mypython --profile=myprofile --user
```
The idea is to be able to configure the kernel to always use a given IPython profile. This could be pretty useful for creating custom versions of the ipykernel.
I realised that there was already almost support for this in the code, I just added a new argument and hooked it up to the internals.
> Add a --profile flag to kernel install

- ipykernel/ipkernel.py
- ipykernel/kernelbase.py
- ipykernel/tests/test_message_spec.py
> ensure status is included in all replies

- docs/changelog.rst
- ipykernel/kernelapp.py
- ipykernel/pylab/backend_inline.py
uses recently discovered (c/o @weathergod) MPLBACKEND env (matplotlib > 1.5) to make inline the 'default' backend, for users who don't call `matplotlib.use()` or `%matplotlib` prior to plotting.
Trigger extra IPython inline setup when inline backend is loaded. We can't call the simpler `ip.enable_matplotlib()` here because this will be triggered during pyplot import, and enable_matplotlib() imports pyplot which isn't ready yet.
This PR is a sibling of https://github.com/matplotlib/matplotlib/pull/6734
With both PRs, users importing matplotlib and using it without calling `%matplotlib <anything>` should get reasonable behavior in all of:
- terminal IPython (including 5, where GUI eventloops won't hang anymore)
- qtconsole (inline backend default, gui backends won't hang)
- notebook (same) …
> Make inline the default matplotlib backend

- docs/changelog.rst
We should be ready to release 4.4 once #159 and #171 are merged.
> Release notes for 4.4

- .travis.yml
- docs/changelog.rst
- ipykernel/pylab/backend_inline.py
- ipykernel/tests/test_kernel.py
Calling `pylabtools.configure_inline_support` on import of the inline backend causes circular imports on Python 2 due to an unnecessary import of pyplot in that function (fixed by ipython/ipython#9850).
This works around that problem by scheduling the configure call to happen at the end of the IPython cell if it fails. The downside of this is that inline figure display formatters will not be registered in the cell containing the import. I'm not *too* bothered by this, because it only affects explicit `display(fig)` calls, not anything triggered by matplotlib's own `show` or implicit draw_if_interactive that provide most figure display. Plus, IPython 5.1 will fix it.
I can come up with a more resilient fix that *moves* much of the inline setup to this repo in the long run, but I think this …
> Workaround circular imports in pylabtools on Python 2

- ipykernel/ipkernel.py
instead of None, which is not a valid value according to IPython
> default to session=0, start=0

- ipykernel/pylab/config.py
This makes changing the dpi more straight forward and
controllable within a context.
For example, the code below now works as expected.
```python
with mpl.rc_context():
mpl.rcParams['figure.dpi'] = 200
mpl.rcParams['figure.figsize'] = (6, 4)
ax = plt.subplot(111)
ax.scatter([1, 2], [1, 2])
```
Without this commit and the accompanying commit in `ipython`,
the `dpi` would be queried directly from the `rcParams` and
this would happen outside the context. With this commit,
Matplotlib creates a figure with the correct `dpi` as a property
and `ipython` will always use that or modify it accordingly.
Also by using `savefig.dpi`, the internal workings of the backend
were slipping into userspace. `InlineBackend` uses the same method
as used for saving but as far as the user is concerned, what is …
> Set the dpi with figure.dpi instead of savefig.dpi

- ipykernel/comm/manager.py
in comm manager
I'm not sure whether every configuration was affected, but I encountered this bug with a python 2.7 setup.
> Bugfix for AttributeError: 'Logger' object has no attribute 'DEBUG'

- ipykernel/kernelbase.py
builtin raw_input does this, so we should, too.
closes https://github.com/jupyter/qtconsole/issues/135
> cast prompt to str in raw_input

- ipykernel/iostream.py
> Added missing `errors` attribute to OutStream (fixes #177)

- ipykernel/tests/test_zmq_shell.py
- ipykernel/zmqshell.py
only the main thread initialized hooks correctly, so other threads would see AttributeError('hooks') on other threads.
closes #180
> fix and test thread local hook registry

- ipykernel/ipkernel.py
abort is a separate action, indicating that the request was not processed, not that a particular error was raised.
Regression in 4.4.
cf https://github.com/jupyter/qtconsole/pull/141
> KeyboardInterrupt is not abort

- docs/conf.py
- docs/index.rst
- ipykernel/zmqshell.py
As per [their blog post of the 27th April](https://blog.readthedocs.com/securing-subdomains/) ‘Securing subdomains’:
> Starting today, Read the Docs will start hosting projects from subdomains on the domain readthedocs.io, instead of on readthedocs.org. This change addresses some security concerns around site cookies while hosting user generated data on the same domain as our dashboard.
Test Plan: Manually visited all the links I’ve modified.
> Convert readthedocs links for their .org -> .io migration for hosted projects

- ipykernel/inprocess/socket.py
- ipykernel/iostream.py
use inproc push/pull to send events to the IOPub thread
- moves all read/write on the buffer to the IOPub thread
- event callbacks are stored in a dict by ID, the ID is sent on the socket to signal event procesing on the thread.
- removes all Locks
- adds IOPubThread.schedule method for the call-this-in-the-thread action,
since events should process immediately in cases (e.g. subprocesses) where
the thread is no longer alive.
closes #198
> remove locks from stdout

- ipykernel/inprocess/tests/test_kernel.py
- ipykernel/kernelbase.py
'cause getpass.getpass takes stream as an argument.
> Add stream parameter to getpass

- ipykernel/comm/comm.py
We already handle this case and raise a more informative exception in `Comm.open()`
This is another thing causing failures from the recent traitlets change.
> Allow Comm.kernel to be None

- ipykernel/zmqshell.py
API addition:
`DisplayPublisher.publish` accepts two new keyword-args: `update: bool, transient: dict` (new args, fully backward-compatible).
Message spec: 
adds third `transient` dict next to data, metadata for data that shouldn't be persisted as part of files.
display_id will be added to this this transient dict by `display(obj, display_id=...)`
IPython PR: ipython/ipython#10048
This is the ipykernel piece of https://github.com/jupyter/jupyter_client/issues/209
cc @rgbkrk
> support transient field, update_display_data

- ipykernel/kernelspec.py
- ipykernel/tests/test_kernelspec.py
- ipykernel_launcher.py
- setup.py
After helping someone who'd shadowed a stdlib module with a file in the cwd (jupyter/help#97), I realised that we could fairly easily make the kernel able to start in such situations.
This PR adds an ipykernel_launcher module which removes the CWD from sys.path and then launches the kernel. There is already code in IPython which adds the CWD back to sys.path before user code runs.
This doesn't get rid of issues with name clashes: modules that we import will shadow modules of the same name in the cwd. So if you wrote math.py, you wouldn't be able to import it. But I think this is easier
for users to understand than the kernel completely failing to start, especially if it's not easy for them to see the logs showing the error.
> Add a launcher module to ignore the CWD for imports while ipykernel starts

- ipykernel/comm/comm.py
- don't mark comm as open if it has no kernel
- don't send close message when kernel is None,
which can happen during interpreter cleanup
closes #210, which appears to have been caused by #205
> further handling of missing comm.kernel

- .gitignore
- .travis.yml
- MANIFEST.in
- setup.cfg
- setup.py
- wheel kernelspec relies on PATH env to find python, which should be okay when installed to sys.prefix, as opposed to system-wide.
- can't use universal wheels anymore, since Python version is in kernelspec name and display name
It would be ideal to get a hardcoded path at install time (https://github.com/pypa/pip/issues/4032), but for envs this should do until that becomes possible.
After this, it should be a lot harder for the native kernelspec to not be installed, which would be ideal. Plus, uninstalling ipykernel will also uninstall the kernelspec.
> install kernelspec in wheels

- ipykernel/kernelbase.py
follow spec: kernels should send busy/idle messages on IOPub during processing of every request
It's ambiguous whether aborted requests are 'processed', but any code that assumes requests get busy/idle could get tripped up by the absence of these messages.  Since the abort is rare, making this case as ordinary as possible is probably best.
> publish busy/idle for aborted requests

- ipykernel/kernelbase.py
See gh-64
With optional parts of the spec, and future additions of message types, the kernel will sometimes get a message that it doesn't know how to handle. This is not generally an error, so we don't need the log message to be so shouty about it.
> Make 'Unknown message' log less scary

- ipykernel/inprocess/ipkernel.py
- ipykernel/zmqshell.py
> fixed #9974 enable  IPython.lib.guisupport.is_event_loop_running_XXX()

- appveyor.yml
No idea if this will actually fix it, but worth a shot.
PS seems to die when there are warning messages, which is odd.
currently triggered when installing tornado 4.5b1
> run appveyor build in cmd, not ps

- ipykernel/kernelapp.py
- ipykernel/parentpoller.py
PID 1 is special, and we can't treat it the same as we do in other cases. When run in Docker, the parent (notebook server) can be PID 1, which results in IPython kernels exiting immediately on start, which manifests as "Kernel Restarting..." and "Kernel appears to have died". This is caused by the parent poller incorrectly detecting that the parent has exited, and shutting down.
Also adds logging for parent-exit-triggered shutdown, which would have helped figure this out much quicker.
closes https://github.com/jupyterhub/kubespawner/issues/31
related: https://github.com/cassinyio/SwarmSpawner/issues/6
cc @yuvipanda
> Disable parent-poller if PID is 1

- ipykernel/_version.py
should be able to release 4.6 after this.
> ipykernel currently implements protocol 5.1

- ipykernel/ipkernel.py
- ipykernel/kernelbase.py
causes deprecation warnings with jupyter_client 5.0 due to the use of naïve datetimes
This metadata is part of ipyparallel and deprecated in ipykernel.
It should be removed in 5.0.
closes jupyter/notebook#2239
> set timezone on `started` metadata when using jupyter_client 5.0

- docs/changelog.rst
Fixing some regressions seen in 4.6.0. I'd like to get this out pretty soon, since there are a couple of small but annoying regressions in recent releases.
cc @JamiesHQ
> Changelog for 4.6.1

- ipykernel/ipkernel.py
- ipykernel/kernelbase.py
- setup.cfg
Work in progress, I want to see if I can use the metadata fields for frontends to opt-in to some extra informations.
Also how backward compatible would it be to have a metadata field on the `complete_request` ? My idea is for testing would have been to have an "Accept:" like field for the kernel to know whether to compute the new completions.
> Use the new IPython completer API

- docs/changelog.rst
- docs/conf.py
> Update changelog for 4.7 release

- ipykernel/displayhook.py
- ipykernel/jsonutil.py
- ipykernel/tests/test_jsonutil.py
There’s ambiguity in Python 2 bytes objects as to whether they are bytes or text, so we have to guess. If it’s valid text (be conservative: only ascii), treat as text, otherwise binary. On Python 3, we don't have to guess.
The guess logic on Python 2 is a bit different from before: Previously, all bytestrings were assumed to be text unless the were specific mime-types.
Upstream can always avoid ambiguity by only passing unicode. Binary data should be passed as base64-encoded unicode objects (https://github.com/ipython/ipython/pull/10739).
Handling of already-base64-encoded unicode objects is unchanged, so providing unicode objects directly as in the ipython PR is a backward- and forward-compatible choice upstream.
> always b64-encode bytes objects on Python 3

- ipykernel/ipkernel.py
- ipykernel/tests/test_kernel.py
In console interfaces, cell magics end on two blank lines.
Closes jupyter/jupyter_console#139
> Fix is_complete response with cell magics

- ipykernel/pylab/backend_inline.py
This PR was sent to fix the behavior of Matplotlib inline mode on Jupyter Notebook.
- before:
- after
Please refer the issue #247
> activate_matplotlib() is not called in _enable_matplotlib_integration()

- ipykernel/eventloops.py
Corresponds to https://github.com/ipython/ipython/pull/10756.  Without this addition, a call to `ip.get_backend('widget')` looked up by ` IPython.core.pylabtools.backend2gui.get` would fail randomly depending on whether it chose `ipympl` or `widget`.
cf https://github.com/matplotlib/jupyter-matplotlib/pull/21#issuecomment-340191921
Temporarily worked around by forcing `backend2gui` to use `ipympl` in https://github.com/matplotlib/jupyter-matplotlib/pull/21/commits/676ea162fdee42f4d6513207c332f81e5e5d7592
> Add widget event loop function

- ipykernel/iostream.py
The background thread cannot be expected to wake properly in the midst of import, so we cannot expect `evt.set` to be called until import completes. In this case, flush is still scheduled, but it is not awaited.
[Reported with PyPy](https://bitbucket.org/pypy/pypy/issues/2690/importing-module-when-pypy-is-kernel-for)
> avoid deadlock on IOPub.flush during import

- ipykernel/eventloops.py
- ipykernel/tests/_asyncio.py
- ipykernel/tests/test_eventloop.py
- ipykernel/tests/utils.py
when interrupted, re-enter eventloop and don't close it (same as all the other eventloops)
Only close the eventloop when we are done for good AND we are responsible for running it.
Also avoid any cleanup when someone else is already running the eventloop (e.g. tornado 5).
closes #263
I'll try add a test for this before it's ready to merge.
> handle KeyboardInterrupt with %gui asyncio

- ipykernel/iostream.py
- events is <del>an OrderedDict</del> a deque
- process all events when an event arrives
avoids fair-queue issues with multiple writes from concurrent threads
This means that sometimes an event will arrive with nothing to do, but that's fine
closes https://github.com/jupyter/qtconsole/issues/246
> process iopub events in order

- ipykernel/ipkernel.py
Came across this as part of some menu-related work for JupyterLab (jupyterlab/jupyterlab#3311).
1. Uses `https` where appropriate (SymPy apparently does not have `https` documentation).
2. Expands the labels to be a bit clearer.
> Update help links.

- ipykernel/connect.py
Putting the Qt console in its own session (and process group, crucially), means that interrupting the kernel doesn't also kill the Qt console.
Closes jupyter/qtconsole#192 (on Python 3)
> %qtconsole launches frontend in new session

- .travis.yml
- appveyor.yml
- ipykernel/inprocess/tests/test_kernel.py
- ipykernel/inprocess/tests/test_kernelmanager.py
- ipykernel/tests/test_connect.py
- ipykernel/tests/test_embed_kernel.py
- ipykernel/tests/test_jsonutil.py
- ipykernel/tests/test_kernel.py
- ipykernel/tests/test_kernelspec.py
- ipykernel/tests/test_message_spec.py
- ipykernel/tests/test_pickleutil.py
- ipykernel/tests/test_serialize.py
- ipykernel/tests/test_start_kernel.py
- ipykernel/tests/test_zmq_shell.py
- ipykernel/tests/utils.py
- setup.py
Switching the test runner Just Works™. I did a quick find-replace pass on the simpler nose asserts, but didn't get all of them, so `nose` is still sitting as a dependency. Nose asserts work fine in pytest, so I don't feel a lot of pressure to finish this up immediately.
- builtin support for showing slow tests (--durations=N slowest test times)
- better error reporting of failures
- Only downside I think is that we lose nose_warnings_filters. I don't know a pytest equivalent, but it does have good [warnings capture](https://docs.pytest.org/en/latest/warnings.html), so adapting the plugin to run as a pytest fixture shouldn't be too much work.
> run tests with pytest

- ipykernel/iostream.py
- ipykernel/kernelapp.py
- ipykernel/kernelbase.py
- ipykernel/zmqshell.py
prepare for tornado 5:
- use thread-local .current over deprecated global .instance
- avoid making IOPubThread loops main thread's instance for a brief period during initialization
> update use of tornado IOLoop.current

- ipykernel/_eventloop_macos.py
- ipykernel/eventloops.py
- ipykernel/zmqshell.py
When any eventloop is running, ipykernel doesn't exit cleanly because we don't stop the main eventloop, we just stop tornado, which isn't running anymore when the eventloop is active. It turns out we have been relying on jupyter-client forcibly terminating kernels that don't shutdown promptly after a polite request.
To solve this, eventloop.exit_hook is added and should be called when exit is requested (the same event where we have been stopping tornado should now stop both eventloops if they are running).
closes #274
closes #282 
TODO:
cc @jbweston and @basnijholt for testing
> clean exit from eventloops

- ipykernel/eventloops.py
It took me several hours to figure this one out!! After ipython/ipython#10756, you can't run `%matplotlib qt5` in any Jupyter client that uses `ipykernel` because it's broken.
This was reported in spyder-ide/spyder#6091 and I created spyder-ide/spyder#6121 to deal with this problem in our side.
> Change registration of the qt eventloop after a similar change in IPython

- .travis.yml
- appveyor.yml
- ipykernel/kernelbase.py
Fixes test failures when tornado runs on asyncio (tornado 5 + Python ≥3.5).
> fix %gui asyncio with tornado 5

- ipykernel/kernelapp.py
workaround libzmq bug when reconnecting sockets with the same identity while *not* in libzmq API call (i.e. kernel busy)
workaround for zeromq/libzmq#2892
closes #270
> set ROUTER_HANDOVER where available

- setup.py
usig absolute paths here causes problems for installs from sdist
We should release 4.8.1 with this, since installations are having issues on Windows.
> avoid absolute paths in data_files

- appveyor.yml
- ipykernel/iostream.py
> Override writable method on OutStream

- .gitignore
I wanted to run exactly what was running on Travis and noticed the pytest cache artifacts were not git ignored.
> include the pytest cache in the gitignore

- ipykernel/iostream.py
- ipykernel/kernelapp.py
I'd like to be able to have access to stdout/stderr the normal way so I threw together the following patch.
I imagine others might want a way to turn this off but I figured I'd share and we can refine further if others are interested.
> kernelapp: Allow preserving stdout and stderr in kernel

- .travis.yml
- ipykernel/pylab/backend_inline.py
- setup.py
This is the sister PR of jupyterlab/jupyterlab#5232.
This PR adds some code so that when the matplotlib inline backend is enabled, one piece of extra metadata (`'needs-background'`) is passed along with each figure. This allows frontends to intelligently display a background behind the figure if it's needed to make the tick labels on the figure legible. This is implemented as so:
Whenever the inline backend calls the `display(fig, metadata)` function, `fig` is first checked to see if it has a transparent background. If it does, the color of each tick label in the figure is checked to see if it's light or dark. If all of the ticks are light, then `'needs-background': 'light'` is added to `metadata`, or if all are dark then `'needs-background': 'dark'` is added. Otherwise, nothing is added …
> Adds metadata to help display matplotlib figures legibly

- CONTRIBUTING.md
- MANIFEST.in
- appveyor.yml
- pyproject.toml
- setup.py
- setup.py updated to use setuptools unconditionally (bdist_egg_disabled for disabling implicit eggs)
- setup.py adds setup_requires needed for the kernelspec step when installing from sdist (fixes #338)
- add release process to CONTRIBUTING.md
> Add release process to CONTRIBUTING.md

- .travis.yml
- appveyor.yml
- docs/changelog.rst
- ipykernel/_version.py
- ipykernel/connect.py
- ipykernel/eventloops.py
- ipykernel/ipkernel.py
- ipykernel/kernelapp.py
- ipykernel/kernelbase.py
- ipykernel/tests/test_async.py
- ipykernel/tests/test_eventloop.py
- ipykernel/tests/test_message_spec.py
- ipykernel/zmqshell.py
- setup.py
allow handlers to return anything acceptable to `gen.maybe_future`
this should include tornado/asyncio coroutines and Futures
counterpart to https://github.com/ipython/ipython/pull/11155
closes https://github.com/jupyter/notebook/issues/3397
> async support

- docs/changelog.rst
- ipykernel/_version.py
- setup.py
- should we also drop 3.4 in IPykernel 5.0 ? 
- Jump version number ot 7.0 to re-sync with IPython ?
> Update version str to be pep 440 compliant, start beta1

- ipykernel/kernelapp.py
On Windows it seems that sys.stdout and possibly sys.stderr can be None. 
This happens at startup of the kernel in Spyder e.g 
https://github.com/spyder-ide/spyder/issues/7842 and multiple duplicates.
The change to flush was introduced in 4.9 with https://github.com/ipython/ipykernel/pull/314
Checking that setout/stderr is not None before flushing seems to be enough to fix the issue for me.
> Check that sys.stdout/err is not None before flushing

- ipykernel/kernelapp.py
- ipykernel/kernelbase.py
- ipykernel/tests/test_message_spec.py
rprint was removed, 5.0 already have this modification.
> IPython 7.x compatibility

- ipykernel/zmqshell.py
- setup.py
See ipython/ipython#9673.
This will disable colours if ipykernel is installed with IPython <5, so
I'm bumping the IPython requirement in setup.py. So this probably can't
be merged until after IPython 5 is released.
-- 
Replace #146
> Remove colors_force flag

- setup.py
This is to reflect that support for python < 3.4 was dropped.
This closes #353
> Remove references to python 2.7

- ipykernel/eventloops.py
I have removed the deadcode requested in issue #349 , I haven't run the tests again , so ping me if that is needed , "I suppose you have an automated testing setup"
> removed deadcode for context

- ipykernel/kernelapp.py
- ipykernel/kernelbase.py
Prior to this change, signal throws an unhandled exception which terminates the ipykernel when ran on a separate thread. This is a problem for embedded applications which need the main thread dedicated to window event polling (eg for GLFW) and would like an ipython kernel running in a separate thread.
With these changes, the unhandled exception is now caught, and displayed as an error, and the kernel keeps running. 
https://github.com/ipython/ipython/issues/11258
> Handle signal exceptions, fix for issue 11258

- ipykernel/ipkernel.py
The JupyterLab inspector can will accept __text/html__ results.  This pull request uses `object_inspect_mime` instead of `object_inspect_text` to inspect objects.  `object_inspect_text` is already calling `object_inspect_mime` to return __plain/text__.  This new feature optionally removes the __text/html__ result data if `enable_html_pager` is False.
This also addresses an old issue #51 and inspects the object once.
> Allow `do_inspect` to return a rich display when `enable_html_pager` is True

- ipykernel/kernelbase.py
- ipykernel/tests/test_kernel.py
- avoids need to truncate comparison because it will always be unique
- avoids message reordering issues with low-resolution timers on Windows
closes #356
closes jupyter/notebook#4052
closes ipython/ipython#11348
> use integer counter instead of loop.time() to preserve message ordering

- docs/changelog.rst
includes missing changelog for 4.10
due to the message-ordering bug in #356, we should make a release promptly.
> changelog for 5.1

- ipykernel/inprocess/ipkernel.py
From v5.0.0, the `Kernel` class contains an `_abort_queues` function invoked when the shell executes a request that generates an exception. This schedules a message, which clears the abort when dispatched. 
This does not work in the `InProcessKernel`. After an exception, all shell execute requests return an "ERROR: execution aborted" message. This is fixed by overriding the `_abort_queues` function in the parent `Kernel` class by a dummy function in the `InProcessKernel` sub-class (it actually replaces the `_abort_queue` function, which doesn't appear to be used any more).
This is a fix for #370.
> Fix compatibility with InProcessKernel

- ipykernel/kernelbase.py
to ensure that the reply is actually sent before we handle the next request
closes #389
closes jupyter/notebook#2748
closes jupyter/notebook#4334
cc @stas00
> flush after sending replies

- ipykernel/codeutil.py
https://www.python.org/dev/peps/pep-0570/
Fixes https://github.com/ipython/ipykernel/issues/406
> Python 3.8: PEP 570 -- Python Positional-Only Parameters

- ipykernel/inprocess/client.py
- ipykernel/kernelbase.py
When using an inprocess kernel, the kernel client calls the `dispatch_shell` method with an `ipykernel.inprocess.socker.DummySocket`
https://github.com/ipython/ipykernel/blob/b81632e0a26671e6b100471282cf49ca4a21e681/ipykernel/inprocess/client.py#L170
This method, however, expects the given stream to have a `flush` method 
https://github.com/ipython/ipykernel/blob/b81632e0a26671e6b100471282cf49ca4a21e681/ipykernel/kernelbase.py#L286
which is not True, for the `DummySocket`. This PR proposes to accept failures for the latter by replacing this line with
```python
try:
stream.flush(zmq.POLLOUT)
except AttributeError:
pass
```
> only flush stream in dispatch_shell if possible

- ipykernel/_version.py
the updates to the protocol add specificity, but ipykernel fully implements the latest spec
> ipykernel implements protocol v5.3

- ipykernel/heartbeat.py
- ipykernel/inprocess/socket.py
- ipykernel/iostream.py
- ipykernel/kernelapp.py
- ipykernel/tests/test_async.py
- ipykernel/tests/test_connect.py
- ipykernel/tests/test_heartbeat.py
- ipykernel/tests/test_io.py
- ipykernel/tests/test_kernel.py
Following [fixes in jupyter_client around zeroMQ thread safety issues](https://github.com/jupyter/jupyter_client/pull/437) I found and closed a couple races in the ipykernel wrapper as well that I found during testing of concurrent patterns with nbconvert.
The first is zeroMQ contexts using `.instance()` which is causes a shared object that's not thread / multiprocessing safe to use. Forcing new context objects to be allocated rather than using a global instance costs a small memory footprint to avoid race condition failures around those context objects.
The second race I found was rare but enough travis builds gave the stack trace below. This points to port binding where a port is picked first, then used in a later call. But that port which was picked could be picked by a concurrent …
> Fixed socket binding race conditions

- ipykernel/heartbeat.py
- ipykernel/kernelapp.py
- restore sys.stdout, etc. prior to closing forwarded io streams.
This prevents errors if print, excepthook, etc. are called during shutdown.
- cleanup heartbeat thread in the right order:
- terminate context from main thread (context.term is the only threadsafe zmq method)
- catch resulting ETERM in thread and close socket
cf #412 and jupyter/nbconvert#1052
> Further cleanup on shutdown

- setup.py
This slightly changes the kernelspec generation so that it only occurs
- upon installation from source (with the full sys.executable)
- or upon wheel generation (with 'python' as executable name)
> Only generate kernelspec when installing or building wheel

- ipykernel/comm/comm.py
The comm can not still be registered when `__del__` is being called:
- if `__del__` is called, the reference count is at 0.
- if the reference count is at 0, then the comm manager doesn't have a reference to the comm. 
This avoids https://github.com/spyder-ide/spyder-kernels/issues/145
> PR: Skip unregistering comm with destructor.

- ipykernel/comm/manager.py
Avoid an issue where the comm sends close messages after being closed.
> Set closed flag

- ipykernel/inprocess/client.py
- ipykernel/inprocess/socket.py
Corrects the wrong placement of the flush method implemented in https://github.com/ipython/ipykernel/pull/405. Don't know how this has happened, but the method should obviously have been implemented for the `DummySocket` class, not for `InProcessKernelClient`...
> Moved InProcessKernelClient.flush to DummySocket

- ipykernel/kernelbase.py
previous flush was not handled at the right time with new async dispatch to ensure control stream priority
Affected case:
- shell request 1 takes a long time to process, is blocking (no async)
- shell request 2 arrives, is received and queued
- control request arrives later, but before shell request 1 is processed, and has not been queued thanks to no `awaits`
It's possible that shell request 2 is in our Python queue, but control request is still waiting one ioloop iteration
to be handled from zmq, and we want to make sure that we still process the control message first.
This is causing test failures in IPython parallel because task abort relies on proper queue priority handling.
> ensure control stream is flushed before processing shell messages

- ipykernel/tests/test_embed_kernel.py
- ipykernel/tests/test_kernel.py
- ipykernel/tests/test_start_kernel.py
- setup.py
Sometimes, `with setup_kernel(cmd) as client:` fails. This repeats the failing tests at most 3 times.
> PR: Add flaky

- ipykernel/eventloops.py
- ipykernel/ipkernel.py
- setup.py
solves https://github.com/ipython/ipython/issues/11602
This is caused by AppNap: https://developer.apple.com/library/archive/documentation/Performance/Conceptual/power_efficiency_guidelines_osx/AppNap.html
This can be desactivated by https://pypi.org/project/appnope/
> PR: Disable AppNap

- docs/changelog.rst
cc @SylvainCorlay @willingc @ccordoba12
> Add release notes for 5.1.3

- ipykernel/kernelapp.py
set eventloop policy to the old default while tornado is not compatible with the new one
same as https://github.com/jupyter/notebook/pull/5047
cross-ref: https://github.com/tornadoweb/tornado/issues/2608
> workaround tornado+py38+windows compatibility issue

- ipykernel/iostream.py
When shutting down, the  flush() method does not work correctly.
> if self.pub_thread.thread.is_alive():
> AttributeError: 'NoneType' object has no attribute 'thread'
> [C 02:15:42.905 NotebookApp] Shutdown confirmed
[I 02:15:42.908 NotebookApp] Shutting down 2 kernels
Error in atexit._run_exitfuncs:
File "/Users/valentin/brew/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 2033, in shutdown
h.flush()
File "/Users/valentin/.pyenv3/tensorflow/lib/python3.7/site-packages/absl/logging/__init__.py", line 891, in flush
self._current_handler.flush()
File "/Users/valentin/.pyenv3/tensorflow/lib/python3.7/site-packages/absl/logging/__init__.py", line 785, in flush
self.stream.flush()
File …
> fix: method flush() in iostream.py 

- ipykernel/pylab/backend_inline.py
closes #231 and https://github.com/matplotlib/matplotlib/issues/8291
We have simplified the process of writing an external backend (which makes sure to not miss these helper functions), but this is the minimal fix to enable figures using the inline backend to be pickled.
> FIX: add missing import from backend_agg

- examples/embedding/inprocess_qtconsole.py
- examples/embedding/inprocess_terminal.py
- examples/embedding/internal_ipkernel.py
- ipykernel/ipkernel.py
The example [inprocess_qtconsole.py](https://github.com/ipython/ipykernel/blob/master/examples/embedding/inprocess_qtconsole.py) is not working with python 3.8 on windows and this PR make it work.
Similar fix as #456: set eventloop policy to the old default while tornado is not compatible with the new one.
I don't follow how this works, so I don't know if this is the right fix (just tried to work out where to put the fix from #456) but at least it should highlight where the issue is! ;)
> Workaround tornado+py38+windows compatibility issue 

- appveyor.yml
- ipykernel/inprocess/tests/test_kernel.py
- setup.py
Further investigates whether the current release meets the need on python 3.8 on windows.
Also changes one of the 3.6 excursions to 3.5. The `setup.py` _claims_ 3.4, but meh, and ensures the (apparently) broken `pytest 5.3.4` is not used...
see also:
- https://github.com/conda-forge/ipykernel-feedstock/pull/52
- https://github.com/conda-forge/ipykernel-feedstock/pull/51
> add py38 and py35 to the appveyor matrix

- setup.py
While it _may_ work, we are not having CI on 3.4 anymore; so it is risky
to indicate it work on 3.4 in setup.py
> Don't indicate support for 3.4.

- ipykernel/inprocess/client.py
`jupyter_client` v6.0.0 requires a control channel.
Fixes https://github.com/jupyter/jupyter_client/issues/523
> Add control channel

- ipykernel/kernelbase.py
I had a case where eventloop was None here (I couldn't find a reproducible example).
It doesn't make sense to enter the eventloop if there is no eventloop.
> PR: Don't enter None eventloop

- ipykernel/ipkernel.py
Fixes #375 
With this change we don't trigger the [deprecation warning](https://github.com/ipython/ipython/blob/fb9c8ca5ccd24a897a79a217d446c8ce7c4a715a/IPython/core/interactiveshell.py#L522) on `ipython.core.InteractiveShell` if we can avoid it.
I started a kernel (using `ipykernel.kernelapp.launch_new_instance`) on this commit, and on the parent b81632e, and connected to it with `jupyter console`, and confirmed that the deprecation message appeared at the prompt when executing code on  b81632e, but was not present on this commit.
> Use shell.input_transformer_manager when available

- ipykernel/kernelbase.py
The original code no longer worked as intended because modern Python versions require `from None` to suppress the previous context, and as a result a long traceback of ipykernel internals was being printed when pressing the Stop button.
This PR fixes the suppression and adds a debug message to make it easier to it easier to understand what happened.
> Produce better traceback when kernel is interrupted

- docs/changelog.rst
The following were listed in the [5.2 milestone](https://github.com/ipython/ipykernel/issues?q=is%3Aclosed+milestone%3A5.2) but already released: #463, #467, #474, #476.
> Update for v5.2

- ipykernel/tests/test_io.py
while trying to package ipykernel for pypy on conda, we've run uncovered a small issue:
```
=================================== FAILURES ===================================
_________________________________ test_io_api __________________________________
def test_io_api():
"""Test that wrapped stdout has the same API as a normal TextIO object"""
session = Session()
ctx = zmq.Context()
pub = ctx.socket(zmq.PUB)
thread = IOPubThread(pub)
thread.start()
stream = OutStream(session, thread, 'stdout')
thread.stop()
thread.close()
ctx.term()
assert stream.errors is None
assert not stream.isatty()
with nt.assert_raises(io.UnsupportedOperation):
stream.detach()
with nt.assert_raises(io.UnsupportedOperation):
next(stream)
with nt.assert_raises(io.UnsupportedOperation):
stream.read()
with …
```
> Add offset argument to seek in io test

- ipykernel/tests/test_kernel.py
- ipykernel/zmqshell.py
Adds an implementation of `system_piped` in `ZMQInteractiveShell` that handles UNC paths on Windows.
Fixes spyder-ide/spyder#10762
The failing test in Travis (`test_complete`) seems unrelated to this.
> PR: Handle system commands that use UNC paths on Windows

- ipykernel/pylab/backend_inline.py
- ipykernel/tests/test_message_spec.py
This looked like an easy fix, so thought I'd give it a go.  Closes #508
> fix ipython display imports

- ipykernel/iostream.py
Solves a bug where calling `print(text, end='')` from `mp.Pool` doesn't print any text until the processing is finished.
eg:
```
import time
from multiprocessing import Process
def f(name):
print('hello', end='')
time.sleep(2)
if __name__ == '__main__':
p = Process(target=f, args=('bob',))
p.start()
p.join()
```
only shows `hello` after 2 seconds and not immediately as expected.
> PR: Flush from process even without newline

- ipykernel/kernelbase.py
- ipykernel/parentpoller.py
- ipykernel/tests/test_kernel.py
This is part of the solution to https://github.com/ipython/ipython/issues/10516.
> Allow interrupting input() on Windows, as part of effort to make pdb interruptible

- ipykernel/kernelapp.py
- ipykernel/tests/test_kernel.py
This is the final fix for https://github.com/ipython/ipython/issues/10516
Without the fix:
1. The test fails.
2. If you open Jupyter on Windows, run `pdb.set_trace()`, and then _in same cell_ run some other code while pdb is still waiting for input, the interrupt button won't work.
With the fix:
1. The test passes.
2. `pdb.set_trace()` is finally interruptible on Windows, even in the scenario described above.
> Make pdb on Windows interruptible

- ipykernel/zmqshell.py
I recently went over [Matplotlib](https://github.com/matplotlib/matplotlib/pull/16706), [Pandas](https://github.com/pandas-dev/pandas/pull/32322) and [NumPy](https://github.com/numpy/numpy/pull/15731), fixing a small mistake in the way that Python 3's exception chaining is used. If you're interested, I can do it here too. I've done it on just one file right now. 
The mistake is this: In some parts of the code, an exception is being caught and replaced with a more user-friendly error. In these cases the syntax `raise new_error from old_error` needs to be used.
Python 3's exception chaining means it shows not only the traceback of the current exception, but that of the original exception (and possibly more.) This is regardless of `raise from`. The usage of `raise from` tells Python to put a …
> Fix exception causes in zmqshell.py

- ipykernel/eventloops.py
This was generating a flush of warnings in qtconsole and Spyder.
Fixes jupyter/qtconsole#332
Fixes spyder-ide/spyder#13275
> Fix QSocketNotifier in the Qt event loop not being disabled for the control channel

- ipykernel/displayhook.py
- ipykernel/inprocess/ipkernel.py
- ipykernel/iostream.py
- ipykernel/ipkernel.py
- ipykernel/kernelapp.py
- ipykernel/kernelbase.py
- ipykernel/tests/test_embed_kernel.py
- ipykernel/tests/test_jsonutil.py
- ipykernel/tests/test_kernel.py
- ipykernel/tests/test_message_spec.py
- ipykernel/tests/test_start_kernel.py
- ipykernel/zmqshell.py
This PR removes the u-prefixes from strings, which are not needed on python 3 only code.
> Remove u-prefix from strings

- ipykernel/kernelbase.py
In the current implementation, `stop_on_error_timeout` doesn't work as expected and instead completely blocks the message queue rather than operating as an async callback as intended.
Explanation:
`stop_on_error_timeout = 0.1`
If we send 100 requests at 1 per 0.01 second, and an error occurs after 0.3 seconds (request 30), this is what is expected to happen:
* requests 1-30 should be queued as normal
* requests 31-40 should be aborted
* requests 41-100 will be queued as normal
What actually happens:
* requests 1-30 are queued as normal
* the message queue blocks for 0.1 seconds
* requests 31-100 are queued as normal
A more extreme case can be seen if you bump this up to `stop_on_error_timeout = 15`. What happens in this case is:
* requests 1-30 are queued as normal
* the message queue …
> Fix stop_on_error_timeout blocking other messages in queue

- ipykernel/kernelspec.py
- ipykernel/tests/test_kernelspec.py
This delivers a basic support of **env** parameter for setting kernel environment variables.
[Optional environment variables](https://jupyter-client.readthedocs.io/en/stable/kernels.html) can be set in kernels, this modification sets multiple environments variables on installation.
If the proposal is accepted, env. var. correctness can be added e.g. based on [Open Group Base Specifications](https://pubs.opengroup.org/onlinepubs/9699919799/)
> Add env parameter to kernel installation

- ipykernel/codeutil.py
- ipykernel/datapub.py
- ipykernel/iostream.py
- ipykernel/ipkernel.py
- ipykernel/log.py
- ipykernel/pickleutil.py
- ipykernel/serialize.py
- ipykernel/zmqshell.py
This PR:
- fixes stack levels for ipykernel's deprecation warnings
- stops using deprecated traitlets api for observing
- uses the ipyparallel interfaces over the deprecated ipykernel variants when available
- uses tornado's IOLoop when pyzmq version is 17 or greater
This greatly minimizes the amount of deprecation warnings from ipykernel.
> Fix stack levels for ipykernel's deprecation warnings and stop using some deprecated APIs

- ipykernel/log.py
The `DeprecationWarning` in this file is missing a comma, so the file can't be loaded. Not used in the normal configuration (since it's deprecated, but while the file is present it should probably be importable).
Found while packaging for Debian since all files get byte-compiled on install, which picked this up.
> Invalid syntax in ipykernel/log.py

- ipykernel/kernelbase.py
Running `git bisect` and `pytest papermill/tests/test_execute.py::TestBrokenNotebook1::test` showed that the error in #568 comes from #539.  The message returned from `kernel_info_request` has status `aborted`.  We are reverting the change to prevent downstream breakage.  cc @glentakahashi  we can revisit your changes in a follow up if you like, making sure that we better understand its ramifications.
```
self = <papermill.clientwrap.PapermillNotebookClient object at 0x7fc060ea5b20>, kwargs = {}
info_msg = {'buffers': [], 'content': {'status': 'aborted'}, 'header': {'date': datetime.datetime(2020, 12, 11, 20, 27, 58, 67808...bc689097e1e214f38609b', ...}, 'metadata': {'engine': '0d33e2cb-93c6-4480-983f-70f97a54b86d', 'status': 'aborted'}, ...}
```
Reverts ipython/ipykernel#539
> Revert "Fix stop_on_error_timeout blocking other messages in queue"

- ipykernel/inprocess/blocking.py
- ipykernel/tests/test_kernel.py
- ipykernel/tests/test_message_spec.py
- ipykernel/tests/utils.py
- setup.py
This implements the same logic [as in jupyter_client](https://github.com/jupyter/jupyter_client/commit/06a32c4f91aba9a8ee6ee76474215aa96e5cd1c1).
Closes https://github.com/jupyter/jupyter_client/issues/601
> Rework wait_for_ready logic

- CONTRIBUTING.md
I couldn't follow current link, and I think this is the link for the same page
> Update URL of Jupyter Contributing Guide

- ipykernel/pylab/backend_inline.py
- ipykernel/zmqshell.py
This removes a circular dependency between ipykernel and IPython. See https://github.com/ipython/ipython/pull/12814
> Add configure_inline_support and call it in the shell

- ipykernel/kernelspec.py
> kernelspec: ensure path is writable before writing kernel.json.

- .github/workflows/ci.yml
- RELEASE.md
- ipykernel/_version.py
- pyproject.toml
- setup.py
- Use PEP517 compliant build tool
- Add CI tests for the release process
- Clean up `setup.py`
- Back to `dev` version
> Clean up release process and add tests

- ipykernel/_version.py
- ipykernel/control.py
- ipykernel/eventloops.py
- ipykernel/inprocess/client.py
- ipykernel/inprocess/ipkernel.py
- ipykernel/iostream.py
- ipykernel/ipkernel.py
- ipykernel/kernelapp.py
- ipykernel/kernelbase.py
This makes the control channel run in a separate thread from the shell channel, so that control messages can be processed concurrently to shell requests.
- this is now the recomended approach in the [Jupyter protocol](https://jupyter-client.readthedocs.io/en/stable/messaging.html#introduction).
>  *For a smoother user experience, we recommend running the control channel in a separate thread from the shell channel, so that e.g. shutdown or debug messages can be processed immediately without waiting for a long-running shell message to be finished processing (such 
as an expensive execute request).*
- this is required for ipykernel to support the Jupyter Debug Protocol in ipykernel: we need to be able to remove and add breakpoints while code is running (or even more importantly, process …
> Run control channel in separate thread

- ipykernel/comm/manager.py
- ipykernel/kernelapp.py
- ipykernel/pickleutil.py
This is to start removing ipython_genutils dependency,
the functionality is identical except this one checks its parameter is a
str.
> Replace import item from ipython_genutils to traitlets.

- ipykernel/ipkernel.py
> Fix Handling of shell.should_run_async

- setup.py
`ipython` 7.17 dropped support for [`python 3.6`](https://ipython.readthedocs.io/en/stable/whatsnew/version7.html#ipython-7-17)
> Update Python Requirement to 3.7

- ipykernel/kernelbase.py
The control stream was not properly flushed before shutting down the ZMQ context.
This fixes CI in `jupyter_client` with the pre-release.
> Flush control stream upon shutdown

- readthedocs.yml
3.5 is EOL and docs builds have been failing.
> bump Python to 3.8 in readthedocs.yml

- ipykernel/kernelspec.py
- ipykernel/tests/test_kernelspec.py
I think that it makes sense to specify (ipykernel) in the kernelspec to differentiate from xeus-python, or other potential python kernels (such as Slicer).
Eventually I would also like to use the proper Python logo for xeus-python.
> Specify ipykernel in kernelspec

- ipykernel/connect.py
- ipykernel/iostream.py
- ipykernel/kernelbase.py
- ipykernel/tests/test_jsonutil.py
As in some of the other Jupyter Repositories; this start to remove
ipython_genutils because of packaging problem in linux distribution
(getting rid of nose).
This is a step toward that.
Note that this changes is slightly stricter in some area where function
would previously accept string/bytes and now only accept one; but as far
as I can tell are generally only used with one of those since we are
Python 3 only.
> Some removal of ipython_genutils.py3compat.

- ipykernel/ipkernel.py
Fixes https://github.com/ipython/ipykernel/issues/540
Follow up to https://github.com/ipython/ipykernel/pull/605#issuecomment-804092466
Ensures that the cell is transformed only once
> Follow up DeprecationWarning Fix

- CHANGELOG.md
- ipykernel/kernelbase.py
Resolves https://github.com/ipython/ipykernel/issues/609
Tested on classic, lab, papermill, testbook, and nteract. The behavior matches 5.4 kernel behavior by default now, with the ability for each interface to set the default abort time if they wish. Testing this with a higher value override worked as expected with requests aborting within the given window of time, though none of the interfaces showed that an abort occurred, they simple show no result. Also `stop_on_error: false` works to ignore the setting (nteract has this on by default for some reason).
@glentakahashi I implemented the suggested change, but when testing if you short circuit the abort future, the run-all in classic and lab will no properly abort already queued cells that were sent with `Run All Cells`. It does work …
> Changed default timeout to 0.0 seconds for stop_on_error_timeout

- ipykernel/kernelbase.py
Followed instructions from https://github.com/ipython/ipykernel/pull/618#issuecomment-809475636 to manually backport #618
> Back port of pull request #618 (Changed default timeout to 0.0 seconds for stop_on_error_timeout)

- ipykernel/debugger.py
This PR implements the inspectVariables request handling in ipykernel, which was the last missing debug request.
> Implemented inspectVariables request

- ipykernel/trio_runner.py
The Trio package renamed their trio.hazmat module to trio.lowlevel.
> Update Trio mode for compatibility with Trio >= 0.18.0

- ipykernel/debugger.py
This fixes the issue in JupyterLab where variables of complex types define d in the notebook are not displayed in the variable panel when the debugger has started.
> Added 'type' field to variables returned by inspectVariables request

- ipykernel/debugger.py
Fixes #629 
@mlucool can you confirm?
> Removed filtering of stack frames for testing

- ipykernel/inprocess/client.py
- ipykernel/inprocess/tests/test_kernel.py
- ipykernel/tests/test_kernel.py
- ipykernel/tests/test_message_spec.py
- ipykernel/tests/utils.py
Use e.g. `kc.get_shell_msg()` instead of `kc.shell_channel.get_msg()`, because the latter is now always async in jupyter_client. The former is a higher-level method that runs `get_msg()` until complete for a blocking client.
> Use channel get_msg helper method

- ipykernel/ipkernel.py
- ipykernel/kernelbase.py
shell_streams is deprecated, but keep it working with deprecation warnings instead of breaking it
and handle debugpy_stream being undefined, since allow_none is True
This is part of avoiding breakage in ipyparallel to smooth the transition.
> make deprecated shell_streams writable

- ipykernel/kernelbase.py
We should not flush the control channel in a shell message handler.
> Fix "Socket operation on nonsocket" in downstream nbclient test.

- ipykernel/zmqshell.py
Mark one long deprecated parameter as deprecated + warnings,
and remove unused variables/imports
> Update of ZMQInteractiveshell.

- ipykernel/connect.py
- ipykernel/datapub.py
- ipykernel/embed.py
- ipykernel/iostream.py
- ipykernel/jsonutil.py
- ipykernel/kernelapp.py
- ipykernel/kernelspec.py
- ipykernel/parentpoller.py
- ipykernel/pickleutil.py
- ipykernel/pylab/backend_inline.py
- ipykernel/serialize.py
- ipykernel/zmqshell.py
This reformat all docstrings in ipykernel to conform to numpydoc.
> DOC: Autoreformat all docstrings.

- .github/workflows/ci.yml
- ipykernel/kernelspec.py
- ipykernel/pickleutil.py
This makes sure that docstring auto formatting won't change anything. Runs only on ubuntu + 3.9
> Build docs only on ubuntu : add jobs to check docstring formatting.

- ipykernel/inprocess/tests/test_kernel.py
- ipykernel/iostream.py
- ipykernel/kernelapp.py
- ipykernel/kernelbase.py
- ipykernel/tests/test_kernel.py
This try to fix a long standing issue that stdout and stderr going
directly to the filedescriptor are not shown in notebooks.
This is annoying when using wrappers around c-libraries, or calling
system commands as those will not be seen from within notebook.
Here we redirect and split the filedescriptor and watch those in threads
and redirect both to the original FD (terminal), and ZMQ (notebook).
Thus output sent to fd 1 & 2 will be shown BOTH in terminal that
launched the notebook server and in notebook themselves.
One of the concern is that now logs and errors internal to ipykernel may
appear in the notebook themselves, so may confuse user; though these
should be limited to error and debug; and we can workaround this by
setting the log handler to not be stdout/err.
This still seem like …
> Try to capture all filedescriptor output and err

- ipykernel/inprocess/client.py
- ipykernel/inprocess/ipkernel.py
- ipykernel/ipkernel.py
- ipykernel/kernelbase.py
- This fixes https://github.com/ipython/ipython/issues/11565 because tornado's wrapping of asyncio is a bit aggressive with creating Task objects which causes them to have a different `contextvars.Context`.
- However, this is a major change. I think this deserves a careful review - and be considered a backward incompatible change.
- If/when this goes in, we should also consider completely getting rid of tornado in ipykernel.
cc @afshin @minrk @Carreau.
Note: tests are passing except for the in-process kernel tests, for which we will need to make more functions async.
> Use native coroutines instead of tornado coroutines

- ipykernel/compiler.py
The cell name is now of the form `/tmp/ipykernel_1789/2216019953.py`, which makes it hard to compare error outputs with a traceback, because the cell name is embedded in it:
```python-traceback
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
/tmp/ipykernel_1789/2216019953.py in <module>
----> 1 foo
NameError: name 'foo' is not defined
```
For instance in nbclient, the new ipykernel will require rewriting our tests because we check strict output equality.
It would be nice to allow setting the cell name by passing it in an environment variable, e.g.:
```
export IPYKERNEL_CELL_NAME="<IPY-INPUT>"
```
This should be enough for tests not involving the debugger.
> Allow setting cell name

- .github/workflows/ci.yml
- ipykernel/zmqshell.py
This correctly applies the rcParams declared in the inline backend configuration when using "%matplotlib inline".
Pinging @blink1073 about it.
> Import configure_inline_support from matplotlib_inline if available

- ipykernel/comm/comm.py
- ipykernel/kernelbase.py
and deprecate instead of break `Kernel._parent_header`.
While testing the 6.0 alpha, I noticed an issue with the OutputWidget, which references the parent header [here](https://github.com/jupyter-widgets/ipywidgets/blob/e0d41f6f02324596a282bc9e4650fd7ba63c0004/ipywidgets/widgets/widget_output.py#L112). #585 changes `_parent_header` to be a nested dict of headers, now that two channels may have different parents, causing the output widget to fail with a KeyError on 'msg_id'.
This is ~understandable because widgets are using a private API, but at the same time there isn't a public API for getting the current parent header, which the output widget needs.
I went with:
- keep `Kernel._parent_header` to mean shell, but with a deprecation
- rename new still-private nested headers trait to …
> Add Kernel.get_parent_header

- ipykernel/control.py
- ipykernel/kernelapp.py
closing sockets while they are still in use by another thread is a recipe for SIGABRT.
skip `close(all_fds=True)` in favor of explicit cleanup of sockets
I believe this fixes the nbclient failures in test_many_parallel_notebooks mentioned [here](https://github.com/ipython/ipykernel/pull/635#issuecomment-827826766).
I'm not sure why that test would have triggered it and not others, but it was readily reproducible for me and doesn't happen anymore after this.
> stop control thread before closing sockets on it

- ipykernel/debugger.py
zmq.ROUTING_ID was added in libzmq 4.2.3 as an alias for IDENTITY.
> fix: Backwards compat with older versions of zmq

- ipykernel/kernelapp.py
Selector is still preferable when ~all out events are on zmq sockets, which must use the add_reader methods missing from Proactor. Tornado 6.1 puts these events in a background thread when Proactor is used, which we can avoid by using Selector.
cf https://github.com/jupyter/notebook/pull/6052
reverts that part of #564
I don't understand the hang mentioned in #563 - if/where that happens and is caused by this patch, it is presumably multiple event loops with events, but only one running (waiting on async events scheduled on a non-running loop will never finish). That should be traceable and avoidable, though, if it can be reproduced.
> Keep preferring SelectorEventLoop on Windows

- ipykernel/kernelbase.py
A fix for this issue: https://github.com/ipython/ipykernel/issues/666
> fix keyboard interrupt issue in dispatch_shell

- ipykernel/iostream.py
- ipykernel/tests/test_io.py
The ` ipykernel.iostream.OutStream` represents an interactive stream and should there have a `isatty` method returning `True`.
Also see https://github.com/ipython/ipykernel/issues/268, https://github.com/ipython/ipykernel/issues/680, https://github.com/willmcgugan/rich/pull/1221
Fixes #680 
Fixes #268
> Make the isatty method of OutStream return True

- ipykernel/kernelbase.py
ensures aborted messages have consistent metadata with real replies
> call metadata methods on abort replies

- ipykernel/iostream.py
Closes #682
Remove the piece of logic that handle `not isinstance(str)` it is a
leftover from Python 2, in pure Python, sys.stdout.write only accepts
str, therefore we have no reason not to do the same.
> Return len of item written to OutStream

- ipykernel/kernelbase.py
While using interactive matplotlib figure, the figure will freeze for 1 seconds very often. This get rid of this freeze.
> Deacrease lag time for eventloop

- setup.py
Just in case this is used by somebody.
> Remove pin on Jedi because that was already fixed in IPython

- ipykernel/eventloops.py
I noticed this when running the Spyder test suite against the newly released ipykernel 6.
> Fix Tk and asyncio event loops

- setup.py
The two dependency-strings for `matplotlib-inline` and `appnope` were merged which lead to errors such as `Invalid constraint (matplotlib-inline (<0.2.0appnope,>=0.1.0) ; platform_system == "Darwin") found in ipykernel-6.0.0rc0 dependencies`.
> [bugfix] fix in setup.py (comma before appnope)

- ipykernel/compiler.py
This seems to be some leftover from old debugger implementation
cc. @JohanMabille
> Remove CachingCompiler's filename_mapper

- ipykernel/eventloops.py
Possible typo in eventloops.py : Changing kernel_shell_stream to kernel.shell_stream fixes this NameError with the MacOSX backend
Using matplotlib backend: MacOSX
ERROR:tornado.application:Exception in callback functools.partial(<function Kernel.enter_eventloop.<locals>.advance_eventloop at 0x108aefe50>)
File "/Users/selasley/venvs/py39/lib/python3.9/site-packages/tornado/ioloop.py", line 741, in _run_callback
ret = callback()
File "/Users/selasley/venvs/py39/lib/python3.9/site-packages/ipykernel/kernelbase.py", line 401, in advance_eventloop
eventloop(self)
File "/Users/selasley/venvs/py39/lib/python3.9/site-packages/ipykernel/eventloops.py", line 327, in loop_cocoa
if kernel_shell_stream.flush(limit=1):
NameError: name 'kernel_shell_stream' is not …
> Fix typo in eventloops.py

- ipykernel/inprocess/ipkernel.py
On some systems, the creation of OutStream instances to handle `stdout` and `stderr` triggers an exception when using the InProcessKernel. This is because the default keyword arguments creating the stream assume there is a file descriptor and calls `fileno`, which triggers an `io.UnsupportedOperation("fileno")` exception. The problem is new to v6. This PR adds `watchfd=False` to the default OutStreams for both `stdout` and `stderr` in the InProcessKernel. This fixes #724.
> Add watchfd keyword to InProcessKernel OutStream initialization

- ipykernel/kernelapp.py
As described in #730, it seems ConnectionFileMixin is expecting `ports` to be List[int].
https://github.com/jupyter/jupyter_client/blob/5742d84ca2162e21179d82e8b36e10baf0f8d978/jupyter_client/connect.py#L386
IPKernelApp is overriding such attribute and changing its type, which generates the error described.
This is the simplest fix I could come up with. Since I am not familiar with the project, please take this as a suggestion.
#Fixes 730
Signed-off-by: Adrian Moreno <amorenoz@redhat.com>
> RFC: kernelapp: rename ports variable to avoid override

- ipykernel/debugger.py
Equivalent of https://github.com/jupyter-xeus/xeus-python/pull/446 for ipykernel
> Implemented richInspectVariable request handler

- ipykernel/iostream.py
- ipykernel/tests/test_io.py
In order to conform with the behavior of `sys.stdout.write` this method should return a `TypeError` rather than a `ValueError`.  This PR also adds an 'f' to the to make the f-string evaluate the `type(string)` and return more helpful information in the exception message.
After some fiddling, I was not able to get the nosetests to pass on my local machine by following the instructions in the READM.md for this repo.  The contributing docs indicated that a pass in actions would be sufficient, but I'm open to suggestions for what I might be doing wrong.
The PR is intended to fix #725
> [WIP] Fix exception raised by `OutStream.write`

- setup.py
Related to #645
The importlib-metadata version was limited to <4 due to a corresponding restriction in the argcomplete package. 
The latest argcomplete patch release has bumped the limit to <5.
Note: ipykernel does not depend on argcomplete directly. 
I could also add an explicit dependency `argcomplete>=1.12.3` to select latest version if that is preferred
> bump importlib-metadata limit for python<3.8

- ipykernel/kernelbase.py
- ipykernel/tests/test_kernel.py
Implements handling of `interrupt_request` [message](https://jupyter-client.readthedocs.io/en/stable/messaging.html#kernel-interrupt), which is now possible due to the control channel being on a separate thread.
Does not implement handling on Windows, which is less likely to be used for remote kernels.
> Add Support for Message Based Interrupt

- .github/workflows/check-release.yml
- CHANGELOG.md
- MANIFEST.in
- RELEASE.md
- ipykernel/_version.py
- pyproject.toml
- setup.cfg
- setup.py
Add adoption of `jupyter-releaser`
> Set up release helper plumbing

- .github/workflows/downstream.yml
It looks like ipykernel master breaks nbclient. I reproduced locally and I can see messages like:
```python
msg = {"shell": {...}, "control": {}}
```
where `...` is a regular message (with its `header` and so on).
Any idea where this could come from?
> Test downstream projects

- README.md
- ipykernel/tests/test_io.py
- ipykernel/tests/test_jsonutil.py
- ipykernel/tests/test_message_spec.py
- setup.cfg
- setup.py
Remove all usages of node except for the stdio streams added by  [`ipykernel`](https://github.com/ipython/ipython/blob/0e4d6390b2174fb1b352a082b72ad387ae696e87/IPython/testing/iptest.py#L334)
> Remove more nose test references

- ipykernel/debugger.py
This implements the deep variable inspection after executing a cell. The output is consistent with that of the variable request, after the code has stopped on a breakpoint.
> Implemented deep variable inspection

- CHANGELOG.md
Automated Changelog Entry for 6.3.0 on master
After merging this PR run the "Draft Release" Workflow on your fork of `jupyter_releaser` with the following inputs
| Version Spec | 6.3.0 |
| Since | 6.2.0 |
> Automated Changelog Entry for 6.3.0 on master

- ipykernel/debugger.py
> Fix undefined variable

- ipykernel/datapub.py
- ipykernel/debugger.py
- ipykernel/inprocess/ipkernel.py
- ipykernel/jsonutil.py
- ipykernel/tests/test_jsonutil.py
Fix #706
This should not be merged before a potential release of jupyter_client with https://github.com/jupyter/jupyter_client/pull/664, otherwise, Matplotlib will not work anymore in Jupyter Notebook/Lab
> Make json_clean a no-op for jupyter-client >= 7

- .github/workflows/ci.yml
- ipykernel/ipkernel.py
- ipykernel/kernelspec.py
debugpy is an optional dependency because only frontends with
debugging support (Jupyter lab) can really use its features.
Fixes: https://github.com/ipython/ipykernel/issues/712
There is also one new test in the CI to check that all tests are passing when debugpy is not installed.
> Make ipykernel work without debugpy

- CHANGELOG.md
Automated Changelog Entry for 6.4.0 on master
After merging this PR run the "Draft Release" Workflow on your fork of `jupyter_releaser` with the following inputs
| Version Spec | 6.4.0 |
| Since | v6.3.1 |
> Automated Changelog Entry for 6.4.0 on master

- pyproject.toml
to get the right debugger metadata in the wheel kernelspec
due to the runtime check added [here](https://github.com/ipython/ipykernel/pull/767/files#diff-c4f6702e977e08e5d1aee47d489ef372ff37913e7e282dbaf269d050f58d56a7R57). The wheel kernelspec currently has an inaccurate `debugger: false` in its metadata, so should probably do a 6.4.1
closes #770
> debugpy is now a build requirement

- CHANGELOG.md
Automated Changelog Entry for 6.4.1 on master
After merging this PR run the "Draft Release" Workflow on your fork of `jupyter_releaser` with the following inputs
| Version Spec | 6.4.1 |
| Since | v6.4.0 |
> Automated Changelog Entry for 6.4.1 on master

- ipykernel/debugger.py
This should help get rid of chatty EncodingWarnings for users on 3.10 with PYTHONWARNDEFAULTENCODING enabled (such as myself) :)
> Add explicit encoding to open calls in debugger

- ipykernel/ipkernel.py
- ipykernel/kernelbase.py
This PR brings to ipykernel a recent IPython PR https://github.com/ipython/ipython/pull/13343 which allows us to customize IPython's responses to `info` and `inspect` messages by specifying which documentation sections we *don't* want. For example, `numpy.sin` returns the following sections:
- Call signature
- Type
- String form
- File
- Docstring
- Class docstring
and with the new `omit_sections` keyword argument, we can for example specify that we are not interested in the `File`, `String form`, and `Type` sections, thereby saving runtime and bandwidth by not generating those documentation sections.
In this present PR, we enable ipykernel's `inspect` message to take advantage of `omit_sections`. If the client provides `omit_sections` in its request, we'll pass it on to IPython.
**Nota …
> Send omit_sections to IPython to choose which sections of documentation you don't want

- ipykernel/debugger.py
Users need to be able to add breakpoints in python standard library source.
For this, the needed flag `DebugStdLib` needs to be added in the `debugOptions` when attaching the debug session.
> Set debugOptions for breakpoints in python standard library source

- ipykernel/debugger.py
This field is now mandatory in the [Jupyter Kernel Protocol](https://jupyter-client.readthedocs.io/en/stable/messaging.html#additions-to-the-dap) and is required in order to move https://github.com/jupyterlab/jupyterlab/pull/10298 forward.
> Added missing excpeionPaths field to debugInfo reply

- CHANGELOG.md
Automated Changelog Entry for 6.6.0 on master
| Version Spec | 6.6.0 |
| Since | v6.5.1 |
> Automated Changelog Entry for 6.6.0 on master

- ipykernel/kernelbase.py
Howdy, I just came across the error reported in #763. I believe that the fix is trivial. My guess is that using an ioloop from either `tornado` or `ioloop` is possible (or is a future possibility), so both exception types should be catered for.
Thanks!
> RF: Handle both asyncio.QueueEmpty and tornado.queues.QueueEmpty

- ipykernel/eventloops.py
Removed writing to the environment inside GUI loop.
Fixes #398 
Makes #399 obsolete.
> Allow pyside2 gui loop

- .github/workflows/check-release.yml
- .github/workflows/ci.yml
- .github/workflows/downstream.yml
- ipykernel/tests/test_kernel.py
- ipykernel/tests/utils.py
- Use `base-setup` and `downstream-test` actions from `jupyterlab/maintainer-tools` to clean up the workflows.
- Add testing for Python 3.10 and pypy
> Clean up workflows

- examples/embedding/internal_ipkernel.py
- ipykernel/comm/comm.py
- ipykernel/compiler.py
- ipykernel/debugger.py
- ipykernel/displayhook.py
- ipykernel/eventloops.py
- ipykernel/gui/gtk3embed.py
- ipykernel/gui/gtkembed.py
- ipykernel/inprocess/blocking.py
- ipykernel/inprocess/channels.py
- ipykernel/inprocess/client.py
- ipykernel/inprocess/ipkernel.py
- ipykernel/inprocess/manager.py
- ipykernel/iostream.py
- ipykernel/ipkernel.py
- ipykernel/kernelapp.py
- ipykernel/kernelbase.py
- ipykernel/parentpoller.py
- ipykernel/pickleutil.py
- ipykernel/tests/__init__.py
- ipykernel/tests/test_async.py
- ipykernel/tests/test_debugger.py
- ipykernel/tests/test_embed_kernel.py
- ipykernel/tests/test_jsonutil.py
- ipykernel/tests/test_kernel.py
- ipykernel/tests/test_kernelspec.py
- ipykernel/tests/test_message_spec.py
- ipykernel/tests/test_pickleutil.py
- ipykernel/tests/test_zmq_shell.py
- ipykernel/zmqshell.py
* `IOError` is `OSError` in python3
* `io.open` -> `open`
* `return str()` -> `return ''` directly
* direct `super()` call
* do not subclass `object`
> Clean python 2 artifacts. Fix #826

- ipykernel/eventloops.py
- setup.py
Fixes  ipython/ipykernel#742
And https://github.com/spyder-ide/spyder/issues/17024
> PR: do_one_iteration is a coroutine

- CHANGELOG.md
Automated Changelog Entry for 6.6.1 on main
| Since | v6.6.0 |
> Automated Changelog Entry for 6.6.1 on main

- ipykernel/debugger.py
- ipykernel/tests/test_debugger.py
If a cell starts with empty lines, they are cleanup as part of the code transformation. This result in breakpoint that can be missed as the number of lines executed will be smaller than the breakpoint line number.
For example,
```python
def f(a, b):
return a + b
f(2, 3)
```
Setting the breakpoint on the last line is not working
Xref: https://github.com/jupyterlab/jupyterlab/issues/11532
This removes the `leading_empty_lines` cleanup transform when a debug session is active.
> Breakpoint in cell with leading empty lines may be ignored

- ipykernel/compiler.py
- ipykernel/debugger.py
- ipykernel/tests/test_debugger.py
- setup.py
> Normalize debugger temp file paths on Windows

- ipykernel/kernelbase.py
This PR aims to start a discussion to add a new message type usage_request/usage_reply as discussed in the last JupyterLab meeting https://github.com/jupyterlab/team-compass/issues/128#issuecomment-971829367
On JupyterLab https://github.com/jupyterlab/jupyterlab/pull/11285 is needed.
cc/ @Carreau
> Add usage_request and usage_reply based on psutil

- ipykernel/debugger.py
Fixes #832.
This reverts #812 , which is responsible for the bug of #832 and another issue where the code suddenly breaks in ipykernel sources. Resuming the execution leads to many errors in the kernel.
> Removed DebugStdLib from arguments of attach

- CHANGELOG.md
Automated Changelog Entry for 6.7.0 on main
| Version Spec | 6.7.0 |
| Since | v6.6.1 |
> Automated Changelog Entry for 6.7.0 on main

- ipykernel/control.py
- ipykernel/debugger.py
- ipykernel/heartbeat.py
- ipykernel/iostream.py
- ipykernel/ipkernel.py
- ipykernel/tests/test_debugger.py
This PR fix the issues of the stored stopped threads when receiving a `stopped` event with `allThreadsStopped` set to True
> Handle all threads stopped correctly

- CHANGELOG.md
Automated Changelog Entry for 6.8.0 on main
| Version Spec | 6.8.0 |
| Since | v6.7.0 |
> Automated Changelog Entry for 6.8.0 on main

- ipykernel/debugger.py
I know a lot of calls to `event_callback` could be factorized out of the `if/else` logic, but I find it more readable this way.
> Fixed event forwarding

- ipykernel/kernelbase.py
- ipykernel/tests/test_message_spec.py
ensures queued messages are aborted, rather than racing with coroutine processing which would complete too soon during asynchronous executions.
Discovered in https://github.com/ipython/ipyparallel/pull/663 where making `do_execute` return a Future would cause abort tests to fail.
> use message queue for abort_queues

- CHANGELOG.md
Automated Changelog Entry for 6.9.0 on main
| Version Spec | 6.9.0 |
| Since | v6.8.0 |
> Automated Changelog Entry for 6.9.0 on main

- ipykernel/kernelbase.py
Fix https://github.com/ipython/ipykernel/issues/864
The hostname is added to the usage reply
> Add hostname to the usage reply

- ipykernel/debugger.py
- ipykernel/ipkernel.py
- ipykernel/kernelbase.py
Fix https://github.com/ipython/ipykernel/issues/862
This adds a configuration `debug_just_my_code` being True by default.
The name has been chosen based on the existing VS Code configuraiton https://docs.microsoft.com/en-us/visualstudio/debugger/just-my-code?view=vs-2022
> Enable standard library debugging via config

- CHANGELOG.md
Automated Changelog Entry for 6.9.1 on main
| Since | v6.9.0 |
> Automated Changelog Entry for 6.9.1 on main

- ipykernel/kernelbase.py
- setup.py
Fixes jupyter/jupyter_client#104.
This should make sure we properly cull all subprocesses at shutdown,
it does change one of the private method from sync to async in order to
no user time.sleep or thread so this may affect subclasses, though I
doubt it.
It's also not completely clear to me whether this works on windows as
SIGINT I belove is not a thing.
Regardless as this affects things like dask, and others that are mostly
on unix, it should be an improvement.
It does the following, stopping as soon as it does not find any more
children to current process.
- Send sigint to everything
- Immediately send sigterm in look with an exponential backoff from
0.01 to 1 second roughtly multiplying the delay until next send by 3
each time.
- Switch to sending sigkill with same backoff.
There is no …
> BUG: Kill subprocesses on shutdown.

- ipykernel/debugger.py
- ipykernel/ipkernel.py
- ipykernel/kernelbase.py
- ipykernel/kernelspec.py
- ipykernel/tests/test_kernel.py
- setup.py
- not the whole process group (`killpg`), which includes kernel itself and possibly parents (closes #872)
- not children which have started their own process groups, which is the standard indicator for "leave me alone when my parent shuts down"
closes #873
> Only kill children in process group at shutdown

- ipykernel/eventloops.py
- This problem is not allowing kernel restarts to complete when the Tk backend is active.
- The error is the following:
```python-traceback
File "/home/carlos/miniconda3/envs/spyder‑stable‑cf/lib/python3.7/site‑packages/ipykernel/kernelbase.py", line 285, in process_control
await result
File "/home/carlos/miniconda3/envs/spyder‑stable‑cf/lib/python3.7/site‑packages/ipykernel/kernelbase.py", line 814, in shutdown_request
content = self.do_shutdown(parent['content']['restart'])
File "/home/carlos/Projects/spyder/github‑repo/external‑deps/spyder‑kernels/spyder_kernels/console/kernel.py", line 105, in do_shutdown
super(SpyderKernel, self).do_shutdown(restart)
File "/home/carlos/miniconda3/envs/spyder‑stable‑cf/lib/python3.7/site‑packages/ipykernel/ipkernel.py …
```
> Catch error when shutting down kernel from the control channel

- CHANGELOG.md
Automated Changelog Entry for 6.9.2 on main
| Since Last Stable | true |
> Automated Changelog Entry for 6.9.2 on main

- CHANGELOG.md
As mentioned in https://github.com/ipython/ipykernel/issues/882#issuecomment-1070798632 this feature only works for POSIX systems.
> Add precision about subprocess stdout/stderr capturing

- ipykernel/iostream.py
I noticed that I'll somewhat unpredictably run into this issue where the kernel prints "IOStream.flush timed out". I found that OutStream.flush() could be called in the I/O thread itself, leading to a wait() that will block for the full 10 second timeout.
I can't reliably reproduce an instance of flush() getting called in the I/O thread, but in my case it looked like a `logger.warning` call inside the asyncio event loop handling was responsible for it.
I think this could be the issue in #334 ?
> Check if the current thread is the io thread

- .github/workflows/ci.yml
- Invoke pytest as `python -m pytest`
- Clean up matrix
> More CI cleanup

- ipykernel/iostream.py
During testing I discovered that writing to stdout and stderr in ipykernel is bottlenecked on scheduling write events on `IOPubThread`. Specifically on [this line](https://github.com/ipython/ipykernel/blob/7f598dd0d62c9112c9918f5651b094fd4fa37e82/ipykernel/iostream.py#L216) which sends a message to notify the thread. Using a lock so we can avoid scheduling every write on the IOPubThread improves the performance more than 20x.
Here is the notebook I used for testing the performance, I start the notebook server with these arguments to prevent it from dropping output `--NotebookApp.iopub_data_rate_limit=1000000000.0 --NotebookApp.iopub_msg_rate_limit=1000000`:
Also in ipynb format: https://gist.github.com/MrBago/06a8e79be3dd2ccbdd1e954a27dd5f86
> Improve performance of stderr and stdout stream buffer

- CHANGELOG.md
Automated Changelog Entry for 6.10.0 on main
| Since | v6.9.2 |
> Automated Changelog Entry for 6.10.0 on main

- ipykernel/ipkernel.py
Method signatures are trivially available for autocomplete requests, I'd like to make them available via the jupyter complete_request.
> Include method signatures in experimental completion results

- ipykernel/inprocess/tests/test_kernel.py
- ipykernel/ipkernel.py
- ipykernel/kernelbase.py
Is seem that few kernel want to make use of cell id for various
reasons.
One way to get the cell_id in the executing context is to make use of
init_metadata but it is marked for removal.
for example in [there](https://github.com/robots-from-jupyter/robotkernel/blob/19b28267406d1f8555ce73b96e7efb8af8417266/src/robotkernel/kernel.py#L196-L205)
Another is to start passing cell_id down.
This is technically a change of API as our consumer may not support more
parameters so we take a peak at the signature, and pass cell_id only if
it is :
- an explicit parameter,
- the function/method takes varkwargs.
We could also start to refactor to pass a metadata object with multiple
fields if this is the preferred route.
One questions is whether and how we want to deprecated not receiving
cell_id as a …
> Try to pass cell id to executing kernel.

- .github/workflows/ci.yml
- ipykernel/eventloops.py
- ipykernel/tests/conftest.py
- ipykernel/tests/test_embed_kernel.py
- ipykernel/tests/test_message_spec.py
- ipykernel/tests/test_pickleutil.py
- pyproject.toml
- setup.py
- Fail on warnings in pytest
- Remove use of deprecated APIs
> Handle warnings in tests

- CHANGELOG.md
Automated Changelog Entry for 6.11.0 on main
| Since | v6.10.0 |
> Automated Changelog Entry for 6.11.0 on main

- ipykernel/iostream.py
Failure seen in https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=483837&view=logs&jobId=bb1c2637-64c6-57bd-9ea6-93823b2df951&j=bb1c2637-64c6-57bd-9ea6-93823b2df951&t=350df31b-3291-5209-0bb7-031395f0baa1
> Do not try to send on iostream if closed

- ipykernel/eventloops.py
- ipykernel/tests/test_message_spec.py
- setup.py
Pinning setuptools as a runtime dependency is often a problem, and setting a minimum of _extremely_ recent setuptools 60 is causing conflicts with e.g. pandas which pins `setuptools<60` (this is making an unsolvable conda environment for me right now).
[migration advice](https://peps.python.org/pep-0632/#migration-advice) suggests using the lighter `packaging` package, and I don't see a reason to use a version pin.
The pkg_resources function is also available for at least 30 versions (setuptools 30), so the `>=60` doesn't seem to have been the right number to use.
Recommend a patch release with the fix, since the dependency in 6.11 is causing installation problems.
> use packaging instead of pkg_resources to parse versions

- CHANGELOG.md
Automated Changelog Entry for 6.12.0 on main
| Since | v6.11.0 |
> Automated Changelog Entry for 6.12.0 on main

- CHANGELOG.md
Automated Changelog Entry for 6.12.1 on main
| Since | v6.12.0 |
> Automated Changelog Entry for 6.12.1 on main

- CHANGELOG.md
Automated Changelog Entry for 6.13.0 on main
| Since | v6.12.1 |
> Automated Changelog Entry for 6.13.0 on main

- .github/workflows/enforce-label.yml
This allows the bot PRs to be automatically labeled as `maintenance`.
> Allow enforce PR label workflow to add labels

- .pre-commit-config.yaml
- ipykernel/inprocess/ipkernel.py
- ipykernel/kernelapp.py
- ipykernel/kernelbase.py
- ipykernel/kernelspec.py
Update for new types provided in `traitlets`.
> Clean up types

- ipykernel/debugger.py
It seems that we can always use the interpreter to get the rich representation of the variable, whether we hit a breakpoint or not. The problem with the current situation where we hit a breakpoint and display an HTML representation of a variable is that the HTML is striped and we get something like `'text/html': '<div>\n<style scoped>...le>\n</div>'` instead of the full HTML. I can't find where it is striped, but if we don't need this branch anyway, can we just get rid of it?
@JohanMabille what do you think?
Also, @fcollonval might have some feedback since he [refactored that part](https://github.com/ipython/ipykernel/commit/73efd890b64145b0d28ea011df58e0745270458b#diff-a30b59f7d3dd6506cbed49059d190fec6a329aed08722be170c5c0dbacfae56dR530-R552).
> Fix richInspectVariables

- CHANGELOG.md
Automated Changelog Entry for 6.13.1 on main
| Since | v6.13.0 |
> Automated Changelog Entry for 6.13.1 on main

- ipykernel/control.py
- ipykernel/kernelbase.py
Fixes https://github.com/ipython/ipykernel/issues/912
This add to the control_thread a map of processes to allow the requesting the cpu_usage in a way psutil excepts (the cpu is only correct if is requested on the same process object).
> Ensure psutil for the  process is accurate

- ipykernel/kernelbase.py
Fixes https://github.com/ipython/ipykernel/issues/935
> use pss memory info type if available for the resource usage reply

- CHANGELOG.md
Automated Changelog Entry for 6.14.0 on main
| Since | v6.13.1 |
> Automated Changelog Entry for 6.14.0 on main

- .github/workflows/ci.yml
- ipykernel/control.py
- ipykernel/iostream.py
I _suspect_  this will reveal failures with the latest tornado 6.2 beta, which is mainly an update to try to deal with asyncio getting rid of the notion of a 'current' event loop that's not running.
> Fix compatibility with tornado 6.2 beta

- pyproject.toml
pyzmq is pulled transitively from jupyter-client, so this will have little to no effect in practice, but it is a direct dependency here.
pyzmq 17 is the version that introduces support for running directly with tornado
it's possible an even more recent version is required
> Explicitly require pyzmq >= 17

- ipykernel/control.py
- ipykernel/iostream.py
I think I misunderstood deprecation warnings about make_current in #956, and this works after all. It may be that all we needed was the removal of `loop.make_current()`
> Back to top-level tornado IOLoop

- CHANGELOG.md
Automated Changelog Entry for 6.15.0 on main
| Since | v6.14.0 |
> Automated Changelog Entry for 6.15.0 on main

- CHANGELOG.md
Automated Changelog Entry for 6.15.1 on main
| Since | v6.15.0 |
> Automated Changelog Entry for 6.15.1 on main

- ipykernel/inprocess/ipkernel.py
Resolves some warnings while using qtconsole!
> `_abort_queues` is no longer async

- CHANGELOG.md
Automated Changelog Entry for 6.15.2 on main
| Since | v6.15.1 |
> Automated Changelog Entry for 6.15.2 on main

- ipykernel/resources/logo-svg.svg
Hi!
This PR adds the python logo in svg format in the resources folder and it is related to https://github.com/jupyterlab/jupyterlab/issues/12997 where we want to fix the blurry icon present when a lot of zoom is made in jupyterlab. 
The asset was downloaded from the official assets of the Python Software Foundation available [here.](https://www.python.org/community/logos/)
> Add python logo in svg format

- ipykernel/eventloops.py
Every time a message is recieved on ipykernel while qt5 is activated, a `QTimer` and a `QSocketNotifier` leak. This closes the memory leak.
Fixes https://github.com/spyder-ide/spyder/issues/19026
> PR: Close memory leak

- CHANGELOG.md
Automated Changelog Entry for 6.15.3 on main
| Draft Release | https://github.com/ipython/ipykernel/releases/tag/untagged-007b3615227d8d0bb624  |
| Since | v6.15.2 |
> Automated Changelog Entry for 6.15.3 on main

- .github/workflows/ci.yml
- ipykernel/inprocess/client.py
Testing against https://github.com/jupyter/jupyter_client/pull/835 (in the prerelease job).
> Add client 8 support

- CHANGELOG.md
Automated Changelog Entry for 6.16.0 on main
| Draft Release | https://github.com/ipython/ipykernel/releases/tag/untagged-f55c22d3b602c89ae86e  |
| Since | v6.15.3 |
> Automated Changelog Entry for 6.16.0 on main

- ipykernel/eventloops.py
The Tk backend leaks causing https://github.com/spyder-ide/spyder/issues/19874
> PR: Destroy tk app to avoid memory leak

- ipykernel/eventloops.py
webagg is enabled in %matplotlib magic in the latest IPython 8.6.0 via this PR:
https://github.com/ipython/ipython/pull/13778
However this trivial change is needed for it to work in an ipykernel environment, otherwise an exception is thrown.
> Enable webagg in %matplotlib

- .github/workflows/ci.yml
- pyproject.toml
Bump officially supported pythons to 3.8-3.11, to reduce maintenance burden and align with conda-forge.
> Update supported pythons to 3.8-3.11

- .github/workflows/prep-release.yml
- .github/workflows/publish-release.yml
- RELEASE.md
Adopt the "Release from Repo" pattern using shared bot credentials.   Admins can now make releases by running workflows from this repository.
> Allow releasing from repo

- ipykernel/comm/__init__.py
- ipykernel/comm/comm.py
- ipykernel/comm/manager.py
- ipykernel/ipkernel.py
This makes use of the comm package, but in a backwards compatible way.
Alternative to https://github.com/ipython/comm/pull/6
See 
* https://github.com/ipython/ipykernel/issues/1026
* https://github.com/ipython/comm/pull/6
> fix: use comm package in backwards compatible way

- .coveragerc
- ipykernel/tests/test_kernel_direct.py
- pyproject.toml
- Remove `debugger` and `eventloops` from coverage since they can't be tested directly.  Debugger is tested indirectly.
- Add more coverage of kernel base
> Clean up testing and coverage

- ipykernel/ipkernel.py
- ipykernel/tests/test_ipkernel_direct.py
IPython rely on configurables being configurables to ... configure things.
Comm seem to insert or return a non-configurable in IPython, that make ipykernel crash in some instances. For example but not limited to:
%config Completer.use_jedi = False
Or trying to use hvplot for example.
This is just a "this is wrong" PR, there should be a proper fix, and I will likely add a hard check in IPython that what is added in configurables is actually a configurables.
This will need a fix in a Comm pacakge.
> Configurables needs to be configurable

- .github/workflows/downstream.yml
- ipykernel/comm/comm.py
- ipykernel/comm/manager.py
Fixes https://github.com/ipython/ipykernel/issues/1040
cf https://github.com/ipython/ipykernel/pull/973
Adds a downstream test for `ipywidgets` and restores the public traits for the `Comm` and `CommManager` classes.
> Fix Comm interface for downstream users

- ipykernel/comm/comm.py
- ipykernel/tests/test_comm.py
Bug introduced in fee98e5, covered by test now.
Closes #1050
> fix: too many arguments dropped when passing to base comm constructor

- ipykernel/comm/comm.py
- ipykernel/tests/test_comm.py
> Don't pass `None` kernels to logging configurable in `Comm`

- ipykernel/eventloops.py
- ipykernel/tests/test_eventloop.py
- pyproject.toml
Addresses #775 
1. Support for Qt 4, 5, and 6, via `PyQt` or `PySide`. Replicated logic from `IPython` (e.g. prefer `PyQt` over `PySide`)
2. Put Qt importing at the level of `enable_gui` so that any import errors show up in the client as opposed to in the kernel's console.
3. Added checks for more helpful error messages / warnings when you can't / aren't going to get the version you're requesting.
4. Included relevant parts of @tacaswell's work in #782
> ENH: add `%gui` support for Qt6

- ipykernel/eventloops.py
- ipykernel/tests/test_eventloop.py
- This is a follow-up PR that fixes the `%matplotlib qt` magic in Spyder.
- Avoid raising `RuntimeError('Kernel already running a Qt event loop.')` in `make_qt_app_for_kernel`. This was the cause of the mentioned failure and it also generated an unnecessary traceback when trying to set another backend:
Instead, replace that raise with a return.
- Remove the Qt4 eventloop because it's ancient and not supported anymore.
- Restore `loop_qt5` function (and make it equal to `loop_qt`) because it's been public API for years and we're using it in Spyder-kernels.
- Avoid raising errors when calling `set_qt_api_env_from_gui` because they are not displayed to clients and instead use prints. Now you get this, for instance:
- Do some cleanup after PR #1054.
> Don't raise error when trying to create another Qt app for Qt eventloop

- ipykernel/iostream.py
- ipykernel/tests/test_io.py
This bug fixes an Exception which was thrown
in OutStream.close() whenever the OutStream was
constructed with watchfd=False.
closes #867 
A regression test was also added to test_io.py.
> Fix Exception in OutStream.close()

- ipykernel/debugger.py
- ipykernel/tests/test_debugger.py
- pyproject.toml
Equivalent of https://github.com/jupyter-xeus/xeus-python/pull/562 for ipykernel.
Draft PR until microsoft/debugpy#1147 is released.
> Add copy_to_globals debug request handling

- ipykernel/ipkernel.py
Following jupyter-server/jupyter_server#1100, this expose the value of JUPYTER_SESSION_NAME environment variable as `__file__`. In _most_ cases, this should reflect the notebook file that correspond to current kernel.
It is not set when the env variable is not set. And it represent the name of file at the time the session was created, it will not reflect renaming of the file.
We could support renaming, but that would require the frontend to send the name of the current file; this would be helpful when we have multiple frontends/documents connected to the same kernel, but this would be out of scope for this PR and a longer discussion to have.
> Expose session start file in __file__.

- ipykernel/eventloops.py
- ipykernel/inprocess/client.py
- ipykernel/kernelapp.py
- pyproject.toml
- Use jupyter_core utilites for `run_sync`
- Drop `nest_asyncio` dep
- Fix typing errors
> Maintenance updates

- ipykernel/ipkernel.py
See https://github.com/jupyter-server/jupyter_server/issues/1198,
setting __file__ will break multiprocessing.
I'm not setting `__notebook__` as things that set this value may note be notebooks.
> Un-expose __file__ and expose __session__ instead.

- ipykernel/kernelbase.py
- ipykernel/tests/conftest.py
- ipykernel/tests/test_ipkernel_direct.py
- ipykernel/tests/test_kernel_direct.py
issue: https://github.com/ipython/ipykernel/issues/1100#issuecomment-1448133194 
Changes in PR
* Added reply content properties for interrupt_request
* `send_interupt_children` => `send_interrupt_children` renaming
* Added test coverage to verify statuses are received
> Fix interrupt reply

- ipykernel/iostream.py
Similar to #115 but for stdout/stderr
This can be useful for a thread to redirect stdout/stderr to a file, while other threads can still write to stdout/stderr.
> Add outstream hook similar to display publisher

- ipykernel/comm/comm.py
- ipykernel/control.py
**Disclaimer:** I work for Databricks, where we patched the control channel to handle jupyter messages like `comm_open` and `comm_msg`.
At Databricks (which uses ipykernel), we often face the situation that customers execute long running pyspark jobs which block the shell channel for minutes or even an hour. In order to provide a better user experience, we unblock some original shell messages by moving them over to the control channel. We successfully did that with `complete_request`, `comm_open` and `comm_msg`.
Part of our fix was changing the comm object so that it gets the parent header from the correct thread. My PR is about that change.
> Support control<>iopub messages to e.g. unblock comm_msg from command execution 

- .readthedocs.yaml
should fix recently failing RTD builds with "Could not import extension sphinx.builders.linkcheck"
> update readthedocs env to 3.11

- .github/workflows/ci.yml
- ipykernel/iostream.py
- ipykernel/tests/test_io.py
- pyproject.toml
When echoing output onto stderr, it should be onto the copy, not the redirected FD, so it only goes to the terminal instead of making an infinite loop, echoing and then capturing and then re-echoing the same output.
I've verified that this works, I just need to work out the tests without messing up pytest output itself.
closes #859
> Avoid echoing onto a captured FD

- ipykernel/inprocess/ipkernel.py
`contextlib.contextmanager` does not always run code following the `yield` statement. this commit adds a finally block to ensure that stdout and stderr are properly restored even in the presence of uncaught exceptions.
> fix: protect stdout/stderr restoration in `InProcessKernel._redirected_io`

- ipykernel/iostream.py
- ipykernel/tests/test_io.py
closes https://github.com/spyder-ide/spyder/issues/21017 
since there's no 'on thread close event', we need to garbage collect event pipes periodically. I don't love this, and the old code was a lot simpler and closed things always and only when needed, but it's not a great pattern to rely on `__del__` to close things, which is why it raises a ResourceWarning.
There will only be something to do when a thread has:
1. triggered an event via print or flush, and
2. closed
so run quite rarely (e.g. 10 seconds)
To see the issue, run:
```python
import warnings
warnings.simplefilter("error", ResourceWarning)
from concurrent.futures import ThreadPoolExecutor
with ThreadPoolExecutor() as pool:
pool.submit(print, 5)
```
> Avoid ResourceWarning on implicitly closed event pipe sockets

- ipykernel/eventloops.py
- ipykernel/inprocess/tests/test_kernelmanager.py
- ipykernel/kernelapp.py
- ipykernel/tests/test_debugger.py
I find the connection file `kernel-<uuid>.json` would be created twice when starting and connecting kernel. I thought this is not as expected since the first time kernel created:
https://github.com/jupyter/jupyter_client/blob/57b11c36b1eceae138cfc6044a2274e2e1caa135/jupyter_client/connect.py#L488
do check this. But the second call, i.e., come from the kernelapp doesn't. Thus that json file would overwrite the previous one. I don't know the general order though, this order is I observed when open a new jupyter notebook.
And this time `kernelname` was not passed. So I never find `kernelname` in connection file, I believe this was a bug.
> Check existence of connection_file before writing

- ipykernel/comm/comm.py
- ipykernel/ipkernel.py
- ipykernel/kernelbase.py
In the previous [PR](https://github.com/ipython/ipykernel/pull/1114) we addressed the problem where iopub `comm` messages generated by control channel have the wrong parent header from shell channel due to hard code. This PR move the logic to `get_parent` (following discussions [here](https://github.com/ipython/ipykernel/pull/1114#issuecomment-1542933370) from @jasongrout and @minrk ) so we remove the hard-coding problem not only for the `comm` messages, but for other iopub messages as well.
> Let get_parent decide the channel to get parent header

- ipykernel/iostream.py
`_watch_pipe_fd()` decodes the incoming data from the pipe using str::decode(). By default this passed the `strict` errors flag to the unicode engine. However, if the pipe command returns binary data this will through a `UnicodeError` exception.
We change the code to explicitly pass the `replace` errors flag, which will replace the output with output that can be displayed on screen.
We also specify the buffer size as a constant so it can be changed for edge cases where the task pipes a lot of output/error text.
> Bugfix: binary stdout/stderr handling

- ipykernel/zmqshell.py
A display hook can handle a publish message, but not yet a clear_output
Upstreaming of: https://github.com/widgetti/solara/pull/132
Follow up of: https://github.com/ipython/ipykernel/pull/1110
Related: https://github.com/ipython/ipykernel/pull/115/files
Would enable https://github.com/jupyter-widgets/ipywidgets/pull/3759 to fully work kernel side.
> feat: let display hook handle clear_output

- ipykernel/kernelapp.py
- ipykernel/tests/test_ipkernel_direct.py
- ipykernel/tests/test_kernelapp.py
This PR lets a connection file specify a port as 0 and then be updated when ipykernel picks a port, as a follow-up to https://github.com/ipython/ipykernel/pull/1127.
In https://github.com/ipython/ipykernel/pull/1127, ipykernel was changed to not overwrite a kernel connection file when it already exists. This broke a pattern we used at Databricks (thanks to @mrbago) that addresses the same handshaking issues as https://github.com/jupyter/jupyter_client/issues/487 and https://github.com/jupyter/enhancement-proposals/pull/66 (i.e., [JEP 66](https://github.com/jupyter/enhancement-proposals/blob/master/66-jupyter-handshaking/jupyter-handshaking.md)). Our pattern was this:
1. The kernel client writes a connection file `connect.json` like the following, where all the port numbers are zero: …
> Merge connection info into existing connection file if it already exists

- ipykernel/debugger.py
In this PR, I make changes to `debugger.py` so that the breakpoints returned in a `debugInfo` response match the breakpoints returned in the most recent `setBreakpoints` request.
**Bug context:**
When a user clicks on a gutter to add/remove a breakpoint, a setBreakpoints request is sent.  The UI changes according to the response of the setBreakpoints request, which gives a list of the breakpoints that were actually added. debugInfo is used to populate the UI breakpoints when a notebook is refreshed. So, it is important that the debugInfo and setBreakpoints information aligns.
Let's say we try to add a breakpoint at a commented out line (say line 2). `debugpy` will infer that that line is not a runnable piece of code, so it will add a breakpoint to the line of code before that (say line …
> Modifying debugger to return the same breakpoints in 'debugInfo' response as 'setBreakpoints'

- ipykernel/eventloops.py
That setting previously caused
`plt.plot(); print("pre"); plt.show(block=True); print("post")` to block after the `show()` call *even* after closing the Matplotlib figure window ("post" was never printed).
The new behavior (printing "post" after the window is closed) is consistent with plain IPython.
The setQuitOnLastWindowClosed call came in (with no additional explanation) in the very first commit implementing qt support (bec2d41, in 2010) and seems to have never been touched since then.
This should close #4367 (which is really an ipykernel issue per https://github.com/spyder-ide/spyder/issues/4367#issuecomment-295026348), which had previously been closed as "can't fix, workaround available".  Attn @ccordoba12 who commented on the spyder issue.
> Don't call QApplication.setQuitOnLastWindowClosed(False).

- ipykernel/iostream.py
`loop.add_callback(loop.stop)` called before the thread starts can get consumed by the run_sync before loop.start, so it won't close the loop. This is causing some tests to hang (e.g. ipython downstream tests), but isn't likely to affect any users at runtime.
The run_sync was added in #1125
> Avoid starting IOPub background thread after it's been stopped

- .github/workflows/ci.yml
- .pre-commit-config.yaml
- ipykernel/comm/comm.py
- ipykernel/comm/manager.py
- ipykernel/connect.py
- ipykernel/eventloops.py
- ipykernel/iostream.py
- ipykernel/ipkernel.py
- ipykernel/kernelapp.py
- ipykernel/kernelbase.py
- ipykernel/pylab/backend_inline.py
- ipykernel/pylab/config.py
- pyproject.toml
Move typing and ruff config into pre-commit and clean up mypy config.
> Clean up typing config

- ipykernel/ipkernel.py
- ipykernel/kernelbase.py
Enhances the `do_execute` method by allowing an optional `cell_meta` parameter, which represents cell metadata. This addition aligns with the Jupyter messaging protocol on [metadata](https://jupyter-client.readthedocs.io/en/latest/messaging.html#metadata), which acknowledges the potential use of metadata in various message types.
Although `metadata` may not be often used, the capability to handle metadata within `do_execute` can expand the kernel's flexibility, especially in scenarios involving complex interactions or custom extensions, as detailed in the [jupyter_client docs](https://jupyter-client.readthedocs.io/en/latest/messaging.html#metadata).
A noteable use case is in the development of [Python wrapper kernels](https://jupyter-client.readthedocs.io/en/latest/wrapperkernels.html#maki …
> Extend argument handling of do_execute with cell metadata

- ipykernel/kernelbase.py
After reviewing #1169 again, this is somewhat a small continuation of the PR. The changes in `_accepts_parameters`, which now checks for two parameters, it seems redundant to verify the signature of `do_execute` for every cell execution request.
In addition, I just moved `cell_meta` and `cell_id` amongst the other `do_execute` parameter assignments for consistency.
> Refactor execute_request to reduce redundancy and improve consistency

- README.md
This PR updates the two `pytest` commands in the README to be the same as those in CI and the various `hatch` commands. It replaces `pytest ipykernel` with `pytest`. An alternative would be to use the more explicit `pytest tests`, but this seems unnecessary.
Problem discovered when following the developer instructions for the first time.
This is my first contribution to `ipykernel` :smiley:
> Update pytest commands in README

- ipykernel/debugger.py
This PR is adding a flag in the `debug_info` response to inform the UI about the support of `copyToGlobals` request.
This should wait for https://github.com/jupyter/enhancement-proposals/pull/93 to be approved.
> Adds a flag in debug_info for the copyToGlobals support

- ipykernel/kernelapp.py
On windows `ipykernel` currently uses `SelectorEventLoop` which is slower than `ProactorEventLoop`. this issue causes many apps like `vscode` use `ipykernel` slow.
Currently, `ipykernel` requires `python` version >=3.8 and `tornado` version >= 6.1 (which can already work with `ProactorEventLoop`)
So this issue can be fixed now
related:
https://github.com/tornadoweb/tornado/issues/2608
https://www.tornadoweb.org/en/stable/releases/v6.1.0.html
https://github.com/ipython/ipykernel/commit/f40d74afe52c4f45749860d293b6f55ac7e0e7d4
> Enable `ProactorEventLoop` on windows for `ipykernel`

- pyproject.toml
Seeing if #1188 is fixed by pinning `pytest-asyncio`.
> Pin pytest-asyncio to 0.23.2

- ipykernel/kernelspec.py
- tests/test_debugger.py
Currently the boolean `debugger` flag in the kernelspec file is determined at build time depending upon whether `debugpy` is installed or not. I think it should always be `True`, on the basis that `ipykernel` supports a debugger in principle and the details of the available debugging are determined at runtime.
This change has no effect on PyPI wheels or conda packages as the flag is always `True` in those, it only affects building from source. Because `debugpy` is a compulsory dependency in the `pyproject.toml` the flag is always `True` except when doing an editable install with build isolation (`pip install -e .`) in which case it is `False`. This is the recommended approach for installing from source specified in the `README.md`, and is how I came across this problem.
I have also …
> Always set debugger to true in kernelspec

- ipykernel/kernelapp.py
Reverts ipython/ipykernel#1184
We will need to add a test for #1190 if we want to re-enable this .
> Revert "Enable `ProactorEventLoop` on windows for `ipykernel`"

- ipykernel/iostream.py
- ipykernel/ipkernel.py
- ipykernel/kernelbase.py
- tests/test_kernel.py
- Fixes https://github.com/jupyterlab/jupyterlab/issues/3936
- Fixes https://github.com/jupyter-widgets/ipywidgets/issues/2358
- Use [`contextvars`](https://docs.python.org/3/library/contextvars.html) to retrieve the parent header of emitting asyncio task
- Use thread identity to retrieve the parent header of emitting thread
- Store iostream buffer per parent header rather than in a single buffer
| Before | After |
|--|--|
| ![before](https://github.com/ipython/ipykernel/assets/5832902/8d558d51-b378-4d7c-a5a0-9a19fbfdda74) | ![after](https://github.com/ipython/ipykernel/assets/5832902/88649e74-890d-4118-b5ae-71aebbb1066a) |
None
> Make outputs go to correct cell when generated in threads/asyncio

- ipykernel/kernelbase.py
Add default value to silent parameter. Aligns with [Jupyter_core](https://jupyter-client.readthedocs.io/en/stable/messaging.html#messages-on-the-shell-router-dealer-channel).
> Fix handling of "silent" in execute request

- .gitignore
Without this, running of pre-commit, adds this file:
node_modules/.cache/prettier/.prettier-caches/8b311690c76070c4437a2a5b4d0e18721f679cd9.json
> Do git ignore of /node_modules/.cache

- ipykernel/kernelbase.py
This fixes a bug where after a while in a Jupyter notebook, we start to see many log lines like this:
```
[IPKernelApp] ERROR | Exception in control handler:
File ".../lib/python3.8/site-packages/ipykernel/kernelbase.py", line 336, in process_control
await result
File ".../lib/python3.8/site-packages/ipykernel/kernelbase.py", line 998, in usage_request
reply_content["kernel_memory"] = sum(
TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'
```
Since the "sum" expects a number (float or int) as elements given to the "sum", we should pass "0" (zero) and not None when we that process id does not exist anymore.
This was tested in an actually running notebook and it fixed the problem:
* no more Exceptions like the one reported above
* correct …
> fix: on exception, return a 0, so that the "sum" still computes

- ipykernel_launcher.py
If use `-m` option, sys.path[0] will be absolute path.
Delete sys.path[0] if it's absolute path. Due to PTH109, I use pathlib. 
We cannot start `python3 -m ipykernel_launcher` in the directory which contains queue.py or zmq.py .
```
ipykernel_launcher.py:13:44: PTH109 `os.getcwd()` should be replaced by `Path.cwd()`
```
--- 
How to reproduce. 
```
cd /tmp
git clone https://github.com/ipython/ipykernel.git
python3 -m pip install -e ./ipykernel
mkdir test
cd test
python3 -m ipykernel_launcher # it works
touch queue.py
python3 -m ipykernel_launcher # error!
```
Error details
```
python3 -m ipykernel_launcher
['/private/tmp/test', '/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python311.zip', '/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.fra …
```
> Fix: ipykernel_launcher, delete absolute sys.path[0]

- tests/test_debugger.py
One of the tests in `test_debugger.py` has been skipped for python >= 3.10 since it was added (#829). The test runs and passes fine for me on Ubuntu using python 3.10.1 and 3.10.13, so here I am re-enabling it to run it on the whole CI matrix.
> Re-enable skipped debugger test

- ipykernel/kernelspec.py
- tests/test_kernelspec.py
Fixes https://github.com/ipython/ipykernel/issues/1198
Frozen modules were extended to modules imported by cPython on startup and enabled by default with the intend of improving startup performance by up to 15% (see https://github.com/python/cpython/pull/28335)
I would suggest we disable frozen modules by default because the performance difference in startup time is ~1% for ipykernel (4 to 5ms compared to total startup time of ~430ms) and this prevents user from getting difficult to diagnose errors during debugging. Of note the same 5ms makes for ~3% of plain Python startup time in 3.11.
Local micro benchmark (1000 repeats each) on Python 3.11 and 3.12.2 (using hyperfine).
Plain Python 3.11 startup:
| Command | Mean [ms] | Min [ms] | Max [ms] | Relative |
|:---|---:|---:|---:|---:|
| …
> Disable frozen modules by default, add a toggle

- ipykernel/eventloops.py
- ipykernel/kernelbase.py
Fixes #1202 by introducing a timed exit to the Tk (on Linux) and Qt (on Windows and Linux) eventloops so `schedule_stop_aborting` can fire after `stop_on_error_timeout` in the kernel's main `io_loop`.
This only affects the eventloops specified, as the others periodically hand control back to the kernel, but Tk (on Linux) and Qt normally wait for a ZMQ socket event to go back to the kernel. The `stop_on_error_timeout` does not fire a socket event, so the timer does not expire and future events are aborted when they should not.
The proposed solution introduces an optional `_schedule_exit` method to eventloops that need it, and makes sure it is called if an eventloop exit is needed for the `stop_on_error_timeout` to fire.
> Eventloop scheduling improvements for stop_on_error_timeout and schedule_next

- ipykernel/inprocess/ipkernel.py
- ipykernel/kernelbase.py
- pyproject.toml
- tests/test_ipkernel_direct.py
- tests/test_kernel.py
Currently when the control channel receives a message on the control stream, it puts it in a `tornado.queues.Queue`, and messages are popped off the queue one a time to be handled using `process_control`. I don't think the queue is necessary as the ZMQ socket/stream queues messages itself.
This PR removes the control queue, simplifying the code. The functions `_flush_control_queue` and `poll_control_queue` are removed as there is no queue to flush or poll. I assume the latter is considered public by its naming convention, but I don't know if any downstream libraries will be relying on its existence.
There are other queues used for the control channel and debugger that I have not looked at yet.
I have ensured that only one control message is handled at a time, to preserve the current …
> Remove control queue

- ipykernel/pickleutil.py
The module is deprecated, but we should still keep it working on Windows.
> Fix side effect import for pickleutil

- pyproject.toml
- tests/test_kernel.py
Fixes #1218.
`test_sequential_control_messages` added in #1210 compares two `datetime`s returned in execute_reply messages. Some downstream libraries (`ipyparallel`) keep them as strings for performance reasons, so here allow this test to accept datetime or strings, otherwise this test is testing the return types rather than the intended sequence of control messages.
Once this passes CI here and is merged, we will need to check that `IPython`s CI also passes before we can be sure that it is fully fixed.
> Allow datetime or str in test_sequential_control_messages

- .github/workflows/ci.yml
- docs/api/ipykernel.inprocess.rst
- examples/embedding/inprocess_terminal.py
- ipykernel/control.py
- ipykernel/debugger.py
- ipykernel/eventloops.py
- ipykernel/inprocess/blocking.py
- ipykernel/inprocess/client.py
- ipykernel/inprocess/ipkernel.py
- ipykernel/inprocess/manager.py
- ipykernel/inprocess/session.py
- ipykernel/inprocess/socket.py
- ipykernel/iostream.py
- ipykernel/ipkernel.py
- ipykernel/kernelapp.py
- ipykernel/kernelbase.py
- ipykernel/zmqshell.py
- pyproject.toml
- tests/conftest.py
- tests/inprocess/test_kernel.py
- tests/inprocess/test_kernelmanager.py
- tests/test_async.py
- tests/test_embed_kernel.py
- tests/test_eventloop.py
- tests/test_io.py
- tests/test_ipkernel_direct.py
- tests/test_kernel_direct.py
- tests/test_kernelapp.py
- tests/test_message_spec.py
- tests/test_pickleutil.py
Supersedes #876.
Closes #656.
IPykernel should not depend on a web server. It uses [Tornado](https://www.tornadoweb.org) as an async framework, but modern Python has better solutions, including standard `asyncio`. Tornado's use in ipykernel involves using a lot of queues and creates complexity that makes maintenance or improvements to the code base harder.
Structured concurrency as introduced by [Trio](https://trio.readthedocs.io) is gaining a lot of traction. [AnyIO](https://anyio.readthedocs.io) brings structured concurrency on top of `asyncio` and acts as an abstraction layer which allows to choose a concurrency backend, such as `asyncio` or `trio`. Major projects have switched to AnyIO, including [FastAPI](https://fastapi.tiangolo.com).
This PR is still a work in progress. I have …
> Replace Tornado with AnyIO

- ipykernel/ipkernel.py
Follow-up to https://github.com/ipython/ipykernel/pull/1213.
This avoid spurious warnings on kernel management operations, like calling `python -m ipykernel install --sys-prefix`.
What do you think?
> Do not import debugger/debugpy unless needed

- ipykernel/ipkernel.py
This fixes the minimum dependency tests following the switch to AnyIO (#1079).
In `IPythonKernel.do_execute` we determine if `cell_id` is supported using
```python
with_cell_id = _accepts_parameters(run_cell, ["cell_id"])
```
or similar. This returns a dict, either `{"cell_id", True}` or `{"cell_id", False}`.
But when testing this we use
```python
if with_cell_id:
```
which gives the correct answer if `cell_id` is supported but the wrong one otherwise. It needs to be
```python
if with_cell_id and with_cell_id["cell_id"]:
```
instead, which is all this PR does.
It happened to work for IPython >= 8.3.0 because of ipython/ipython#13600 so that `cell_id` is always accepted, but failed for IPython <= 8.2.0.
> Correctly handle with_cell_id in async do_execute

- ipykernel/_eventloop_macos.py
Fixes #1124 which is that the use of `%matplotlib osx` crashes `ipykernel` and downstream libraries whereas `ipython` is fine.
The fix is to specify the `argtypes` of each `objc_msgSend` call just before the call. This is consistent with how `ipython` successfully handles it. I have tested this manually using `spyder` and `jupyter console`, `qtconsole`, `lab` and `nbclassic`: using `ipykernel 6.29.4` (the latest release) they all crash, using this branch they all work as expected.
This PR is opened against the `6.x` branch rather than `main` as issue #1235 means it is not possible to test any `matplotlib` GUI loops on `main`. It would be good to get this into a release (6.29.5?) as soon as possible and not have to wait for #1235 and the other AnyIO fallout issues to be fixed beforehand. …
> Fix use of "%matplotlib osx"

- tests/conftest.py
Fixes #1252.
When using anyio `MemoryObjectReceiveStream` and `MemoryObjectSendStream` we must explicitly close them when we have finished with them. This wasn't necessary with anyio 4.3.0 but is with 4.4.0 as otherwise warnings/errors are issued which break our CI.
This is only actually an issue in CI as our only explicit use of memory object streams is in `TestSession`.
> Explicitly close memory object streams

- ipykernel/jsonutil.py
...
/usr/lib/python3.13/site-packages/ipykernel/jsonutil.py:29: in <module>
datetime.strptime("1", "%d")
/usr/lib64/python3.13/_strptime.py:573: in _strptime_datetime
tt, fraction, gmtoff_fraction = _strptime(data_string, format)
/usr/lib64/python3.13/_strptime.py:336: in _strptime
format_regex = _TimeRE_cache.compile(format)
/usr/lib64/python3.13/_strptime.py:282: in compile
return re_compile(self.pattern(format), IGNORECASE)
/usr/lib64/python3.13/_strptime.py:270: in pattern
warnings.warn("""\
E   DeprecationWarning: Parsing dates involving a day of month without a year specified is ambiguious
E   and fails to parse leap day. The default behavior will change in Python 3.15
E   to either always raise an exception or to use a different default year (TBD).
E   To avoid trouble, add a …
> Avoid a DeprecationWarning on Python 3.13+

- pyproject.toml
test_pylab with IPython 8.24 and above raises DeprecationWarnings about backend{s,2gui} being deprecated, causing test failures. Add them into the IPython list so they are ignored.
> Catch IPython 8.24 DeprecationWarnings

- pyproject.toml
CI is failing with
```
ERROR: while parsing the following warning configuration:
ignore:trio.MultiError is deprecated since Trio 0.22.0:trio.TrioDeprecationWarning
This error occurred:
DeprecationWarning: The `hash` argument is deprecated in favor of `unsafe_hash` and will be removed in or after August 2025.
```
using `attrs` 24.1.0 and `trio` 0.26.1. Related issue in `trio` is python-trio/trio#3053. This PR ignores the new warning.
> Ignore warning from trio

- ipykernel/_eventloop_macos.py
This is a forward port of PR #1237 from the `6.x` branch to `main`. I think it was supposed to happen automatically as part of the semi-automated release process but there were a number of problems with that.
Note that this isn't actually usable until #1235 is fixed.
> Specify argtypes when using macos msg

- ipykernel/kernelapp.py
- ipykernel/parentpoller.py
- tests/test_parentpoller.py
New behaviour: poll getppid and exit if this value is no longer equal to the original parent pid.
For backwards compatibility: keep old behaviour when parent_pid is 0 or not given.
Parentpoller only watches for parent change to pid 1 (init), but in modern linux environments processes are usually reparented to the systemd user session process. In this situation, ipykernel never noticies that its parent has exited.
jupyter-client already sets JPY_PARENT_PID with the pid of the parent process. We could trust this environment variable directly, but in this change, it is only used if it is equal to the actual parent id when the poller starts. (A side effect: if the parent dies quickly enough, ipykernel does not notice.)
Fixes #517
> Detect parent change in more cases on unix

- ipykernel/kernelbase.py
`process_shell_message` has
```python
assert socket is None
```
for the default subshell, so passing `shell_socket` here results in:
```python
socket = self.shell_socket
...
assert socket is None
socket = self.shell_socket
```
> socket must be None, not shell_socket for default shell

- .github/workflows/ci.yml
- pyproject.toml
Drop support for Python 3.8 as it reached end-of-life on 2024-10-07.
> Drop support for Python 3.8

- ipykernel/kernelbase.py
control channel always copies
closes #1278
> restore zero-copy recv on shell messages

- tests/test_subshells.py
Improve robustness of subshell concurrency tests. This is difficult to do as the tests run reliably fine on my dev machine so I am looking at what could theoretically improve the situation and trying it out in CI.
I have moved the `import time` to before starting the time-sensitive subshell code as this should be better than importing it in one subshell (taking an unknown amount of time) or importing it in both subshells at the same time (GIL contention?). If this is not sufficient I could add some threaded synchronisation to the start of the subshell test code to remove any timing variability in sending/receiving zmq messages.
> Improve robustness of subshell concurrency tests

- ipykernel/kernelbase.py
- tests/test_kernel_direct.py
no version of ipython parallel without these methods will work with ipykernel 7 anyway, so might as well remove them since they can never be used.
Restores `should_handle` to be sync in the default implementation (it only returns True now that the ipyparallel code is removed), which was an unnecessary breakage. It is _allowed_ to be async in subclasses.
alternative to the updated deprecation messages in #1272
> remove deprecated ipyparallel methods now that they are broken anyway

- ipykernel/inprocess/ipkernel.py
- ipykernel/inprocess/socket.py
- ipykernel/iostream.py
- tests/test_io.py
- tests/test_kernel.py
all sockets are explicitly sync until/except we are in the coroutines that will await them, whereas there was an ambiguous mixture of sync and async sockets before
- consistent behavior of send for child pipe and main process sockets
- avoids unsafe assumption that send is greedy on async sockets
- avoids potential issues creating async objects in one thread, then using them in another in a different event loop
- always creates/uses the right types, regardless of input socket
- address some typing lint
found while working on https://github.com/ipython/ipyparallel/issues/895
> fix mixture of sync/async sockets in IOPubThread

- .github/workflows/downstream.yml
Main branch test was cancelled after 6h, which is a waste of resources.
> Add 20 min timeout dowstream ipyparallel

- tests/test_subshells.py
Second attempt to improve robustness of subshell concurrency tests, building on #1285. Using a `threading.Barrier` at start of subshell code execution in tests that are sensitive to timing so that they are tolerant of, for example, a shell message that takes slightly longer to send/receive than normal.
I am hoping to fix ipython/ipython#14545 eventually.
> Improve robustness of subshell concurrency tests using Barrier

- ipykernel/kernelapp.py
- pyproject.toml
> Misc type annotations

- .github/workflows/ci.yml
Closes #1298.
This PR replaces jupyterlab/maintainer-tools's base-setup action with setup-python.
> Remove base setup

- ipykernel/kernelapp.py
> Fix ipykernel install

- tests/test_kernel.py
The parent thread has to live for the duration of the child thread, otherwise the parent thread exits before the child thread and disappears from the active threads, causing it to be removed from `thread_to_parent` and eventually leading to messages not being routed to the right cell:
https://github.com/ipython/ipykernel/blob/41a965eb35b3364a56e5f1e827d7e3a9580c0213/ipykernel/ipkernel.py#L781-L794
@krassowski Could you confirm? I saw that while working on #1291.
> Fix test_print_to_correct_cell_from_child_thread

- tests/test_subshells.py
This  keep failing downstream in IPython. It's annoying. I hope this will give an idea as to why. Otherwise can we mark the test as xfail ?
If not I"ll stop testing in IPython if I break ipykernel.
> More Informative assert

- .pre-commit-config.yaml
- CHANGELOG.md
I think some if those changes are wrong, as `[foo]` is valid markdown when the link is defined later, but here we actually want square brackets.
> Manually update mdformat pre-commit and run it.

- .pre-commit-config.yaml
- ipykernel/trio_runner.py
- tests/utils.py
small to make it easy to review.
> Manually update Codespell and fix new errors.

- ipykernel/_version.py
- ipykernel/embed.py
- ipykernel/inprocess/channels.py
- ipykernel/iostream.py
- ipykernel/kernelapp.py
- ipykernel/pickleutil.py
- ipykernel/thread.py
- tests/test_kernelapp.py
In order to support proper execution after resuming from an embedded kernel, we have to make sure that we can revert the IO alterations by the kernelapp using the `close()` method. The following fixes were made:
* Call `close` before `embed` returns
* Don't write the extra character on `OutStream` `close()` to pipe for watching thread if it's already dead or missing
* Add new variable `closed` so that "close" can be called multiple times without any error
* Don't use `__stdout__` and `__stderr__` at all
* Keep `blackhole` reference around so that the watching thread's pipe file descriptors do not get accidentally closed when the object is garbage collected (it happens now because it is not stored in `__stdout__`)
* Keep old IO variables and restore them when exiting
* More robust …
> properly close OutStream and various fixes

- .github/workflows/downstream.yml
It says its for branch protection, but branch protection can already requires multiple checks, and it creates an arbitry extra failure, which is anyway ignored as downasrteam is failing on main.
So it's just extra noise IMHO.
> Remove downstream_check

- ipykernel/kernelbase.py
- tests/test_debugger.py
[JEP92](https://github.com/jupyter/enhancement-proposals/pull/92/files) added support for optional features to be included in kernel info reply messages via the `supported_features` attribute, with subshells and debugger being examples. We are already using it for subshells, this PR also adds `debugger` to the list of `supported_features` if `debugpy` is importable.
Corresponding documentation PR in `jupyter_client` for messaging protocol is jupyter/jupyter_client#1045.
This replaces the use of `kernel_info_reply['debugger']` which should be considered deprecated but cannot be removed until downstream libraries adopt reading the `supported_features` rather than `debugger` attribute directly.
> Use supported_features=['debugger'] in kernel info reply

- ipykernel/datapub.py
- pyproject.toml
Mostly those are not real error, and  should allow us to update ruff without major noises/code changes.
- There are a lot of `%` formatting, moving to f- would be good but a churn, 
and 
- ruff 0.2.0 prefers fixture without `()`, so I can't apply the patch without current pre-commit to complain.
> Ignore or fix most of the remaining ruff 0.9.6 errors

- ipykernel/kernelbase.py
- pyproject.toml
See discussion in #1272; It is not deprecated, but being able to always know you can (and must) await should be simpler in the long run.
Deprecating now is not the point, but I want to cover our bases, so that we are more confident later when and if we want to enforce those await.
In particular many of those branches are not covered in our tests – and I don't even know wether they were ever taken;
After changing some of the base methods to be async, it breaks qtconsole, spyder kernel and a few things– so only emitting warnings for now.
A few other things use the `if awaitable(...):` pattern but are a bit more complicated, and some do not date back to 2021, so those will be dealt with separately.
> Suggest to make implementations of some function always return awaitable

- pyproject.toml
- as seen in https://github.com/ipython/ipykernel/pull/1322
- as tracked in https://github.com/tox-dev/sphinx-autodoc-typehints/issues/523
> Pin sphinx to resolve docs build failures

- ipykernel/kernelapp.py
- tests/test_connect.py
We sometime get
```
FAILED tests/test_connect.py::test_port_bind_failure_gives_up_retries - pytest.PytestUnraisableExceptionWarning: Exception ignored in: <function Socket.__del__ at 0x7efe22e4d760>
File "/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/zmq/sugar/socket.py", line 185, in __del__
warn(
ResourceWarning: Unclosed socket <zmq.asyncio.Socket(zmq.PUB) at 0x7efe1eb32820><F48>
```
This adds a tracemalloc fixture for the crashing test module in order to try to narrow that down. I'm thorn between restart the tests here until we have the failure; or merge and see once we get the error in another PR and then remove the fixture once we've fund the culprit.
--- 
The only zmq.PUB I can find is iopub, and we don't seem to be closing …
> Try to debug non-closed iopub socket

- ipykernel/embed.py
- ipykernel/ipkernel.py
- ipykernel/kernelapp.py
- pyproject.toml
- tests/test_embed_kernel.py
- tests/test_ipkernel_direct.py
- tests/test_kernel_direct.py
- tests/test_kernelapp.py
There are few chances we will ever use them again.
Also a small refactor and unskip of trio test using trio nursery.
> Delete always skipped test, fix trio test, fix framelocal has not .clear()

- tests/conftest.py
As we are recommending upstream to use asyn, mught as well do it ourselves a well.
Plus this makes sure our test suite tests async
> Make our own mock kernel methods async

- .github/workflows/ci.yml
- .readthedocs.yaml
- tests/test_eventloop.py
I think this is an anti pattern,
1. we are already using flaky, so flaky test should be marked as such.
2. if it fails on first run and pass on --lf, this indicate that the
test are relying on a global state that should either:
- be investigated
- is known, and then should be given a specific marker to be ran separately.
in addition:
4. `--lf` reruns the test without qt5 or qt6, so don't actually rerun many test. 
5. If there is a segfault in qt5 (which there is in main), then qt6 is not ran _at all_ – and actually there were failures !
So this is actually bad as _it hides errors_.
If at least it was `cov:test||cov:test --lf` it would make more sens, but here it's plainly wrong.
-- 
This is just a suggestion and my reasoning.  See #1323,  and thanks to @davidbrochart for pointing out that …
> Don't rerun test with --lf it hides failures.

- pyproject.toml
Most of these seem old, and pass locally, so I want to see if they are still necessary on CI.
> Check ignores warnings are still relevant.

- pyproject.toml
It is replaced by License-expression (which is exclusive with license that we used, so can't just replace for now).
https://packaging.python.org/en/latest/specifications/core-metadata/#license-expression
> Licence :: * trove classifers are deprecated

- pyproject.toml
- tests/conftest.py
- tests/test_connect.py
- tests/test_ipkernel_direct.py
See the explanation;
we don't want to use TRACEMALLOC=20 on the fulll test suite, and enable for a single test is a bit more complicated.
See explanation in fixture itself.
> Another try at tracking down ResourceWarning with tracemalloc.

- pyproject.toml
This makes is way easier to renanble mypy on a single file, or duplicate this entry en reenable a single type of checks.
This means that new files will also be checked by mypy.
> Move mypy disablinging error codes on a per-file basis

- ipykernel/zmqshell.py
`tqdm` has an incorrect detection of ZMQInteractiveShell when launch via a scheduler that bypass IPKernelApp. Think of JupyterHub cluster spawners and co.
As of end of Feb 2025, the maintainer has been unresponsive for 5 months, to our fix, so we implement a workaround. I don't like it but we have few other choices.
See https://github.com/tqdm/tqdm/pull/1628
> TQDM workaround due to unresponsive maintainer

- ipykernel/kernelbase.py
In the current "dispatch_shell", if we fail the "should_handle" check during execution, we will not send any message to ioPub indicating shell status. For a client waiting for an "idle" status update, this could block the state machine and cause a hang command. This PR fixes the bug by publishing an "idle" status when the "should_handle" check fails.
> [Bugfix] Set shell idle when message skipped by "should_handle" in "dispatch_shell"

- tests/inprocess/test_kernelmanager.py
- tests/test_embed_kernel.py
- tests/test_kernel.py
- tests/test_start_kernel.py
Use the `@pytest.mark.flaky` fixture in place of the `@flaky.flaky` decorator, to modernize the code and improve compatibility with other plugins providing the feature such as `pytest-rerunfailures`.
Fixes #1410
> Replace `@flaky.flaky` decorate with pytest fixture

- CHANGELOG.md
Remove links in the changelog to github milestones that no longer exist. This fixes the current failures in the `link_check` CI run.
> Remove links in changelog to github milestones that no longer exist

- CHANGELOG.md
Backport of #1415 from `main` to `6.x` branch to fix `link_check` tests.
> Backport: Remove links in changelog to github milestones that no longer exist

- ipykernel/kernelbase.py
- tests/test_debugger.py
Forward port of #1416 from `6.x` branch to `main`. Fixes processing of control messages sequentially rather than concurrently.
> Forward port from 6.x: Correct use of asyncio.Lock to process a single control message at a time

- ipykernel/_version.py
After the branch manipulations a few weeks ago, we need to update the `__version__` to be the latest in the `7.x` series not `6.x` series.
Fixes ipython/ipython#14953.
> Use correct `__version__` on `main` branch after branch manipulations

- tests/inprocess/test_kernelmanager.py
- tests/test_embed_kernel.py
- tests/test_kernel.py
- tests/test_start_kernel.py
Backport PR #1411 from `main` to `6.x`, updating the `flaky` test fixture.
> Backport PR 1411 to 6.x

- .github/workflows/downstream.yml
Try reinstating the `jupyter_client` downstream tests but with exclusions, until the appropriate PRs are merged downstream - see #1422.
> Reinstate jupyter_client downstream tests with exclusions

- docs/api/ipykernel.rst
- ipykernel/kernelbase.py
- ipykernel/utils.py
- pyproject.toml
- tests/test_kernel.py
PR #1414 replaced the private member variable `Kernel._parent_ident` with threadsafe support of separate parent idents per thread (subshell) using `ContextVar`s. This caused a failure downstream in JupyterLab (jupyterlab/jupyterlab#17785) as it reads the private `_parent_ident`. Upon investigation there are a number of downstream projects that read this variable, presumably due to copy-paste-modify of `ipykernel` code to override the behaviour. So rather than break those projects, here I am reintroducing `Kernel._parent_ident` as a shim for backward compatibility that can be called the same way as before. It uses a lazy-evaluated read-only dictionary.
I have also added a new test to check that `Kernel.get_parent` and `Kernel._parent_ident` perform as expected.
> Continue to support `Kernel._parent_ident` for backward compatibility

- .github/workflows/ci.yml
- .github/workflows/downstream.yml
- ipykernel/iostream.py
- ipykernel/jsonutil.py
- pyproject.toml
- tests/test_kernel.py
- tests/test_subshells.py
Drop support for Python 3.9 on `main` branch. We would normally continue to support a Python version until its end of life, which is next month, but the next release from `main` will be 7.0.0 and I don't intend to make bug fix releases on the 7.x branch for Python 3.9 so it is cleaner to not do a release in the first place. Note that `ipython` has already dropped support for Python 3.9 and 3.10.
The `6.x` branch will continue to support Python 3.9 if any further bug fix releases are required on that branch.
> Drop support for Python 3.9
